src/objects/Application__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Holds the running or paused mode. Holds the namespace prefix needed to normalize custom buttons URLs and javascript. Holds the credentials needed to manage the Broker running user context. #774 formerly OAuth Setting.</description>
    <fields>
        <fullName>Prefix__c</fullName>
        <description>Raw namespace prefix, eg &apos;ns&apos; or null</description>
        <inlineHelpText>What is my namespace prefix?</inlineHelpText>
        <label>Namespace Prefix</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Application</label>
</CustomObject>

src/classes/ApexClassConfigExtensionTest.cls
@IsTest class ApexClassConfigExtensionTest {

    @TestSetup static void testSetup() {
        //act
        new PostInstallHandler().onInstall(null);
        
        //assert
        System.assertNotEquals(null, Application__c.getOrgDefaults().Id, 'Wrong id.');
    }
    
    static testmethod void coverCode() {
        //arrange
        ApexClass apexClass = [
            SELECT Id
            FROM ApexClass
            WHERE Name = 'WiretapService'
            AND NamespacePrefix = :Application__c.getOrgDefaults().Prefix__c
        ];
        
        //act
        Test.setCurrentPage(Page.ApexClassConfig);
        ApexPages.StandardController controller = new ApexPages.StandardController(apexClass);
        ApexClassConfigExtension extension = new ApexClassConfigExtension(controller);
        
        //assert
        System.assert(!ApexPages.hasMessages(), 'Wrong messages.');
    }

}