src/objects/Application__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Holds the running or paused mode. Holds the namespace prefix needed to normalize custom buttons URLs and javascript. Holds the credentials needed to manage the Broker running user context. #774 formerly OAuth Setting.</description>
    <fields>
        <fullName>PrefixBar__c</fullName>
        <description>String that would prefix a Salesforce Object to namespace it, eg &apos;ns__&apos; or null</description>
        <inlineHelpText>What prefix should I use to fully qualify a Salesforce Object, including the trailing underscore underscore?</inlineHelpText>
        <label>Namespace Prefix Bar (ns__)</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrefixDot__c</fullName>
        <description>String that would prefix an Apex Class to namespace it, eg &apos;ns.&apos; or null</description>
        <inlineHelpText>What prefix should I use to fully qualify an Apex Class, including the trailing dot?</inlineHelpText>
        <label>Namespace Prefix Dot (ns.)</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RunAsAccessToken__c</fullName>
        <description>Roaring and ready access token that can be used to invoke Salesforce APIs.</description>
        <label>Run As Access Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application</label>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Message__c.object
<CustomObject>
    <customHelpPage>MessageHelp</customHelpPage>
    <fields>
        <fullName>Exception__c</fullName>
        <inlineHelpText>If the process threw an exception when handling this message, what was the error text?</inlineHelpText>
        <label>Exception</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>What stage of its lifecycle is this message at?</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Buffer</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reprocess</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Which Step is this message destined for?</inlineHelpText>
        <label>Step</label>
        <referenceTo>Step__c</referenceTo>
        <relationshipLabel>Messages</relationshipLabel>
        <relationshipName>Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Message</label>
    <nameField>
        <displayFormat>N-{0000000000}</displayFormat>
        <label>Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Slot__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>High performance iteration without FieldPermissions</description>
    <label>Slot</label>
</CustomObject>

src/objects/Step__c.object
<CustomObject>
    <label>Step</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MessageViewExtension.cls
public with sharing class MessageViewExtension {
    
    static MessageModel dmlModel;
    ApexPages.StandardController controller;
    public Message__c Message {get; set;}
    public List<Message__c> Children {get; set;}
    public ApexClassModel.Definition Definition {get; set;}
    
    public MessageViewExtension(ApexPages.StandardController controller) {
        this.controller = controller;
    }
    
    @RemoteAction static public void handleRestart(Id messageId, Long duration, String exceptions, String cause) {
        //execanon results
        update new Message__c(
            Id = messageId,
            Status__c = 'Started',
            ExecuteDuration__c = duration,
            Exception__c = exceptions.abbreviate(SObjectType.Message__c.Fields.Exception__c.Length),
            Cause__c = cause.replaceAll('[\r]?\n', '\r\n').abbreviate(SObjectType.Message__c.Fields.Cause__c.Length)
        );
    }
    
    public PageReference doInit() {
        
        if (this.controller.getId() != null) {
            //get away from standard controller
            PageReference redirect = Page.MessageView;
            redirect.getParameters().put('mid', this.controller.getId());
            redirect.setredirect(true); //prevents internal error
            return redirect;
        }
        
        String mid = ApexPages.currentPage().getParameters().get('mid');
        
        this.Message = [
            SELECT Id, Name, CreatedDate, Status__c, Route__c, ExecuteDuration__c, Exception__c, Cause__c, Event__c, JobId__c, ParentId__c, Slot__c
            FROM Message__c
            WHERE Id = :mid
            ALL ROWS
        ];
        
        this.Children = [
            SELECT Id, Name, CreatedDate, Status__c, Route__c, ExecuteDuration__c, Exception__c
            FROM Message__c
            WHERE ParentId__c = :mid
            ALL ROWS
        ];
        
        try {
            //resolve class name
            String apexTypeName = this.Message.Route__c;
            Step__c step = Step__c.getValues(this.Message.Route__c);
            if (step != null) apexTypeName = step.ApexTypeName__c;
            
            //unit tests skip cache
            if (Test.isRunningTest()) this.Definition = new ApexClassModel.Definition(Type.forName(apexTypeName));
            else if (!Test.isRunningTest()) this.Definition = ApexClassSetModel.loadCache().get(apexTypeName);
            
        } catch (Exception e) {
            ApexPages.addMessages(e);
        }
        
        try {
            dmlModel = new MessageModel(this.Message);
            Type.forName(DoDml.class.getName()).newInstance();
        } catch (Exception e) {
            ApexPages.addMessages(e);
        }
        
        return null;
    }
    
    public PageReference showService() {
        MessageModel model = new MessageModel(this.Message);
        
        try {
            PageReference detailView = model.showService();
            return detailView;
            
        } catch (MessageModel.ModelException e) {
            ApexPages.addMessages(e);
            return null;
        }
    }
    
    public PageReference showData() {
        MessageModel model = new MessageModel(this.Message);
        
        try {
            PageReference detailView = model.showRecordData();
            return detailView;
            
        } catch (MessageModel.ModelException e) {
            ApexPages.addMessages(e);
            return null;
        }
    }
    
    public ApexPages.Component getRestart() {
        Component.Apex.CommandButton commandButton = new Component.Apex.CommandButton();
        commandButton.value = 'Restart Message';
        commandButton.onclick = 'this.className = "btnDisabled";this.disabled = "disabled";setTimeout(function() {' + javascript() + '}, 50);return false;';
        return commandButton;
    }
    
    public String javascript() {
        String bar = Application__c.getOrgDefaults().PrefixBar__c;
        String dot = Application__c.getOrgDefaults().PrefixDot__c;
        String sid = Application__c.getOrgDefaults().RunAsAccessToken__c;
        if (bar == null) bar = '';
        if (dot == null) dot = '';
        if (sid == null) sid = '';
        
        String mid = ApexPages.CurrentPage().getParameters().get('mid');
        Map<String,Object> parameters = new Map<String,Object>{'ToService' => 'Services.RestartMessageId', 'RecordId' => mid};
        return (''
            + 'var mid = "' + mid + '";'
            + 'var bar = "' + bar + '";'
            + 'var sid = "' + sid + '";'
            + 'var mark = new Date().getTime();'
            + 'var command = \'new ' + Enqueue.class.getName() + '().invoke(new Process.PluginRequest((Map<String,Object>)Json.deserializeUntyped(\\\'' + Json.serialize(parameters) + '\\\')));\';'
            + 'sforce.connection.init(sid, "/services/Soap/u/35.0");'
            + 'var response = sforce.apex.executeAnonymous(command);'
            + 'if (response.success == "false") {' //started, persist any fatal error and refresh
            + '    Visualforce.remoting.Manager.invokeAction('
            + '        $RemoteAction.MessageViewExtension.handleRestart,'
            + '        mid,'
            + '        new Date().getTime() - mark,'
            + '        response.exceptionMessage,'
            + '        response.exceptionStackTrace,'
            + '        function() {window.location.reload();},'
            + '        {}'
            + '    );'
            + '} else {' //completed, redirect back to list view, or just refresh
            + '    window.location.reload();'
            + '}'
        ).replaceAll('    ', ' ');
    }
    
    public class DoDml {
        public DoDml() {
            //roaring and ready access token
            Application__c setting = Application__c.getOrgDefaults();
            setting.RunAsAccessToken__c = ConfigureController.refreshAccessToken();
            upsert setting;
            
            //avoids dml in action method
            dmlModel.healExtendedStatus();
        }
    }
    
}