src/objects/AuditEntry__c.object
<CustomObject>
    <customHelpPage>AuditEntryCsh</customHelpPage>
    <fields>
        <fullName>AuditGroup__c</fullName>
        <inlineHelpText>What Audit Group is this entry written into?</inlineHelpText>
        <label>Audit Group</label>
        <referenceTo>AuditGroup__c</referenceTo>
        <relationshipLabel>Audit Entries</relationshipLabel>
        <relationshipName>AuditEntries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>GroupIdentifier__c</fullName>
        <formula>AuditGroup__r.GroupIdentifier__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>XXX</inlineHelpText>
        <label>Group Identifier</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <formula>Step__r.Position__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>What position in the sequence was the AuditWriter Step that the message passed through?</inlineHelpText>
        <label>Position</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sequence</label>
        <referenceTo>Sequence__c</referenceTo>
        <relationshipLabel>Audit Entries</relationshipLabel>
        <relationshipName>AuditEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stamp__c</fullName>
        <formula>AuditGroup__r.Stamp__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>XXX</inlineHelpText>
        <label>Stamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What AuditWriter Step did the message pass through?</inlineHelpText>
        <label>Step</label>
        <referenceTo>Step__c</referenceTo>
        <relationshipLabel>Audit Entries</relationshipLabel>
        <relationshipName>AuditEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Audit Entry</label>
    <nameField>
        <label>Audit Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Audit Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AuditGroup__c.object
<CustomObject>
    <customHelpPage>AuditGroupCsh</customHelpPage>
    <fields>
        <fullName>AuditInitializerConfig__c</fullName>
        <inlineHelpText>What record configures the AuditInitializer Step that the message was passing through?</inlineHelpText>
        <label>Audit Config</label>
        <referenceTo>AuditInitializerConfig__c</referenceTo>
        <relationshipLabel>Audit Groups</relationshipLabel>
        <relationshipName>AuditGroups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>GroupIdentifier__c</fullName>
        <inlineHelpText>XXX</inlineHelpText>
        <label>Group Identifier</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stamp__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <inlineHelpText>XXX</inlineHelpText>
        <label>Stamp</label>
        <type>DateTime</type>
    </fields>
    <label>Audit Group</label>
    <nameField>
        <label>Audit Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Audit Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AuditInitializerConfig__c.object
<CustomObject>
    <customHelpPage>AuditInitializerConfigCsh</customHelpPage>
    <fields>
        <fullName>StaticGroupIdentifier__c</fullName>
        <description>Enter any static business key (eg INVOICE, PAYSLIP, etc) to  describe the grouping.  Alternatively ,leave blank  to enable a system generated identifier.</description>
        <inlineHelpText>What text (eg INVOICE, PAYSLIP, etc) will be used to name the Audit Groups created at this step?</inlineHelpText>
        <label>Static Group Identifier</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Audit Config</label>
    <nameField>
        <label>What does this step do?</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Audit Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process__c.object
<CustomObject>
    <customHelpPage>ProcessHelp</customHelpPage>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sequence__c.object
<CustomObject>
    <customHelpPage>SequenceHelp</customHelpPage>
    <label>Sequence</label>
    <nameField>
        <label>Sequence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Step__c.object
<CustomObject>
    <fields>
        <fullName>Position__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Position</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipName>Steps</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Step</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AuditWriterTest.cls
@IsTest private class AuditWriterTest{

    static testmethod void hasTheCorrectLimits() {
        //assert
        Integer expectedLimits = 50;
        Integer actualLimits = new AuditWriter.ESB().Limits;
        System.assertEquals(expectedLimits, actualLimits);
    }
    
    
    private static testmethod void callingInvokeThrowsExpectedExceptionWhenCannotAccessEntryPointGuid() {
        //arrange
        String sequenceName  = 'AuditWriterSequence';
        Integer thePosition =  1;
        Id theId  = '000000000000000AAA';
        Process__c auditWriterProcess = ProcessObject.generateOne(AuditWriter.class);
        
        Sequence__c sequence = new Sequence__c(Name = sequenceName);
        insert sequence;
    
        Map<String,Object> parameters = new Map<String,Object>{
            // '__EntryPointGuid' => '1234567abcde',  // null EntryPointGuid
            'esb__Id' => theId
        };
        
        //act
        Boolean actualFlagException =  false;
        String actualMessage;
        try {
            Type reflector = AuditWriter.class;
            List<Map<String,Object>> results = new Broker.Wrapper(reflector, parameters, null).invokeMain().Outputs;
        } catch (Exception e) {
            actualFlagException =  true;
            actualMessage = e.getMessage();
        }
      
        // Assert
        Boolean expectedFlagException = true;
        System.assertEquals(expectedFlagException, actualFlagException);
        
        String expectedMessage = 'Unable to access the Entry Point GUID';
        System.assert( actualMessage.contains(expectedMessage) );
    }
    
    private static testmethod void callingInvokeThrowsExpectedExceptionWhenCannotAccessStep() {
        //arrange
        String sequenceName  = 'AuditWriterSequence';
        Integer thePosition =  1;
        Id theId  = '000000000000000AAA';
        Process__c auditWriterProcess = ProcessObject.generateOne(AuditWriter.class);
        
        Sequence__c sequence = new Sequence__c(Name = sequenceName);
        insert sequence;
    
        Map<String,Object> parameters = new Map<String,Object>{
            '__EntryPointGuid' => '1234567abcde',
            'esb__Id' => theId
        };
        
        //act
        Boolean actualFlagException =  false;
        String actualMessage;
        try {
            Type reflector = AuditWriter.class;
            List<Map<String,Object>> results = new Broker.Wrapper(reflector, parameters, null).invokeMain().Outputs;
        } catch (Exception e) {
            actualFlagException =  true;
            actualMessage = e.getMessage();
        }
      
        // Assert
        Boolean expectedFlagException = true;
        System.assertEquals(expectedFlagException, actualFlagException);
        
        String expectedMessage = 'Unable to access the Step';
        System.assert( actualMessage.contains(expectedMessage) );
    }

    private static testmethod void callingInvokeInsertsExpectedAuditWriterEntries() {
        //arrange
        String theIdentifier1 = 'BALLS';
        String theIdentifier2 = 'CROW';
       
        String sequenceName  = 'AuditSequence';
        Integer positionA2 =  1;
        Id theId  = '000000000000000AAA';
        Process__c auditWriterProcess = ProcessObject.generateOne(AuditWriter.class);
               
        Sequence__c sequence = new Sequence__c(Name = sequenceName);
        insert sequence;
        
        Step__c stepA2 = new Step__c(Sequence__c = sequence.Id, Position__c = positionA2, Process__c = auditWriterProcess.Id);
        insert stepA2;
 
        AuditInitializerConfig__c config1  = new AuditInitializerConfig__c(
            StaticGroupIdentifier__c = theIdentifier1
        );
        insert config1;
         
        AuditInitializerConfig__c config2  = new AuditInitializerConfig__c(
            StaticGroupIdentifier__c = theIdentifier2
        );
        insert config2;
        
        AuditGroup__c auditGroup1  = new AuditGroup__c(
            AuditInitializerConfig__c = config1.Id,
            GroupIdentifier__c =  theIdentifier1,
            Stamp__c = System.Now()
        );
        insert auditGroup1;
        
        AuditGroup__c auditGroup2  = new AuditGroup__c(
            AuditInitializerConfig__c = config2.Id,
            GroupIdentifier__c =  theIdentifier2,
            Stamp__c = System.Now()
        );
        insert auditGroup2;
 
        List<Object> auditGroupIds = new List<Object>{ auditGroup1.Id, auditGroup2.Id };
 
        Map<String,Object> parameters = new Map<String,Object>{
            'esb__Id' => theId,
            '__EntryPointGuid' => '1234567abcde',
            'esb__AuditGroupIds' => auditGroupIds,
            '__SequenceName' => sequenceName,
            '__Position' => positionA2
        };
        
        //act
        Type reflector = AuditWriter.class;
        List<Map<String,Object>> results = new Broker.Wrapper(reflector, parameters, null).invokeMain().Outputs;
        
        //assemble
        List<AuditEntry__c> auditEntries = SalesforceObjectSet.listAll(AuditEntry__c.SObjectType);
        
         
        Boolean actualAuditGroup1 = false;
        Boolean actualAuditGroup2 = false;
        String actualParametersSerialized1;
        String actualParametersSerialized2;
        for (AuditEntry__c  auditEntry : auditEntries) {
            if (auditEntry.AuditGroup__c == auditGroup1.Id) {
                actualAuditGroup1 = true;
                actualParametersSerialized1 = auditEntry.Parameters__c;
            }
            if (auditEntry.AuditGroup__c == auditGroup2.Id) {
                actualAuditGroup2 = true;
                actualParametersSerialized2 = auditEntry.Parameters__c;
            }
        }
        String actualSequenceName;
        Boolean actualParameters = ( actualParametersSerialized2 != null);
 
        
            
        // Assert
        Integer expectedResultsSize = 1;
        Integer actualResultsSize = results.size();
        System.assertEquals(expectedResultsSize, actualResultsSize);
        
        Integer expectedAuditEntrySize = 2;
        Integer actualAuditEntrySize = AuditEntries.size();
        System.assertEquals(expectedAuditEntrySize, actualAuditEntrySize);

        Boolean expectedAuditGroup1 = true;
        Boolean expectedAuditGroup2 = true;
        Boolean expectedParameters = true;
        String expectedSequenceName = sequenceName;
        System.assertEquals(expectedAuditGroup1, actualAuditGroup1);
        System.assertEquals(expectedAuditGroup2, actualAuditGroup2);
        System.assertEquals(expectedParameters, actualParameters);
        System.assertEquals(actualParametersSerialized1, actualParametersSerialized2);
        System.assert(actualParametersSerialized1.contains(expectedSequenceName));
    }

}