src/objects/AuditEntry__c.object
<CustomObject>
    <customHelpPage>AuditEntryCsh</customHelpPage>
    <fields>
        <fullName>AuditGroup__c</fullName>
        <inlineHelpText>What Audit Group is this entry written into?</inlineHelpText>
        <label>Audit Group</label>
        <referenceTo>AuditGroup__c</referenceTo>
        <relationshipLabel>Audit Entries</relationshipLabel>
        <relationshipName>AuditEntries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Hops__c</fullName>
        <inlineHelpText>How many hops were there when this entry was written?</inlineHelpText>
        <label>Hops</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <formula>Step__r.Position__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>What position in the sequence was the AuditWriter Step that the message passed through?</inlineHelpText>
        <label>Position</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sequence</label>
        <referenceTo>Sequence__c</referenceTo>
        <relationshipLabel>Audit Entries</relationshipLabel>
        <relationshipName>AuditEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What AuditWriter Step did the message pass through?</inlineHelpText>
        <label>Step</label>
        <referenceTo>Step__c</referenceTo>
        <relationshipLabel>Audit Entries</relationshipLabel>
        <relationshipName>AuditEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Audit Entry</label>
    <nameField>
        <label>Audit Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Audit Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AuditGroup__c.object
<CustomObject>
    <customHelpPage>AuditGroupCsh</customHelpPage>
    <label>Audit Group</label>
    <nameField>
        <label>Audit Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Audit Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sequence__c.object
<CustomObject>
    <customHelpPage>SequenceHelp</customHelpPage>
    <label>Sequence</label>
    <nameField>
        <label>Sequence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Step__c.object
<CustomObject>
    <fields>
        <fullName>Position__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Position</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Step</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AuditWriter.cls
public with sharing class AuditWriter {
    
    public String Parameters;
    
    /**
     * @docs ProcessAudit.html
     */
    public class ESB {
        public String Tag = 'Enterprise Service Bus';
        public String Name = 'Audit Writer';
        public String Description = 'Stores the message parameters under an Audit Group.';
        public String Icon = 'pencil_add';
        public String HelpUrl = new PageReference('/apex/Csh?topic=ProcessAudit').getUrl();
        public Integer Limits = 50; //leave half of 200 (Total number of SOQL queries issued)
    }
    
    public class AuditWriterException extends Exception {}
    
    override public String toString() {
        if (!SObjectType.AuditEntry__c.Createable) throw new SalesforceObject.CrudException('!SObjectType.AuditEntry__c.Createable');
        
        Map<String,Object> parameters = (Map<String,Object>)Json.deserializeUntyped(this.Parameters);
        List<Map<String,Object>> parametersList = new List<Map<String,Object>>();
        
        Integer parametersOrder = (Integer)parameters.get('__Hops');
        parametersOrder = (parametersOrder != null) ? parametersOrder : 1;
        
        String entryPointGuid = (String)parameters.get('__EntryPointGuid');
        if (String.isBlank(entryPointGuid)) {
            throw new AuditWriterException('Unable to access the Entry Point GUID');
        }
                
        //derive the Step
        List<Step__c> steps = [
            SELECT Id, Position__c, Sequence__c
            FROM Step__c
            WHERE Sequence__r.Name = :(String)parameters.get('__SequenceName')
            AND Position__c = :(Decimal) parameters.get('__Position')
        ];
        if (steps.size() == 0) {
            throw new AuditWriterException('Unable to access the Step');
        }
        Step__c step = steps[0];
 
        //write audit entry for every audit group identifier
        List<Object> collection = (List<Object>)parameters.get('esb__AuditGroupIds');
        
        if (collection != null) {
            List<Id> auditGroupIds = new List<Id>();
            for (Object c : collection) {
                if  (c != null) {
                  auditGroupIds.add((Id) c );  
                }
            }
            Set<Id> filteredAuditGroupIds = (new Map<Id,AuditGroup__c>([
                SELECT Id, Name
                FROM AuditGroup__c
                WHERE Id IN :auditGroupIds
            ])).keySet();
        
            String serializedParameters = System.Json.serializePretty(parameters);
            List<AuditEntry__c> auditEntries =  new List<AuditEntry__c>();
            for (Id auditGroupId  : filteredAuditGroupIds) {
                auditEntries.add( new AuditEntry__c(
                    Step__c = step.Id,
                    Sequence__c = step.Sequence__c,
                    Hops__c = parametersOrder,
                    AuditGroup__c     = auditGroupId,
                    EntryPointGuid__c = entryPointGuid,
                    Parameters__c    = serializedParameters
                ));
            }
            insert auditEntries;
        }

        parametersList.add(parameters);
        
        return Json.serialize(parametersList);
    }
}