src/objects/BoomerangConfiguration__c.object
<CustomObject>
    <fields>
        <fullName>Chain__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Chain</label>
        <referenceTo>Chain__c</referenceTo>
        <relationshipLabel>Boomerang Configuration</relationshipLabel>
        <relationshipName>BoomerangConfiguration</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Boomerang Configuration</label>
    <nameField>
        <label>What does this step do?</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boomerang Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Chain__c.object
<CustomObject>
    <label>Chain</label>
    <nameField>
        <label>Chain Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ChainStep__c.object
<CustomObject>
    <fields>
        <fullName>Chain__c</fullName>
        <label>Chain</label>
        <referenceTo>Chain__c</referenceTo>
        <relationshipLabel>ChainSteps</relationshipLabel>
        <relationshipName>ChainSteps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>ChainSteps</relationshipLabel>
        <relationshipName>ChainSteps</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>ChainStep</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ChainSteps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Process__c.object
<CustomObject>
    <customHelpPage>ProcessHelp</customHelpPage>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ChainStepAfterInsertTest.cls
@isTest public class ChainStepAfterInsertTest {
	
	//dummy configurable process
	public class MockProcess implements Process.Plugin {
		
		//this needs SOME, ANY SObject for configuration that can be inserted with NO required fields
		public Process.PluginDescribeResult describe() {
			Process.PluginDescribeResult plugin = new Process.PluginDescribeResult();
			plugin.Description = '{"eda__configurable":"' + Schema.SObjectType.BoomerangConfiguration__c.Name + '"}';
			return plugin;
		}
		
		public Process.PluginResult invoke(Process.PluginRequest request) {
			Map<String,Object> notification = request.inputParameters;
			return Utility.convert(new List<Map<String,Object>>{notification});
		}
		
	}
	
	static testMethod void testChainStepConfigurationIsCreatedWhenInserted() {
		//arrange
		Process__c process = new Process__c(Name = 'ChainStepAfterInsertTest.MockProcess');
		insert process;
		
		Chain__c chain = new Chain__c(Name = 'TestChain');
		insert chain;
		
		//act
		ChainStep__c chainStep = new ChainStep__c(Chain__c = chain.Id, Process__c = process.Id);
		insert chainStep;
		
		//requery after trigger
		chainStep = [SELECT Id, Configuration__c FROM ChainStep__c WHERE Id = :chainStep.Id];
		
		//assert
		String expectedId = Schema.SObjectType.BoomerangConfiguration__c.KeyPrefix; //this needs to be some config record
		String actualId = chainStep.Configuration__c;
		System.assert(actualId.startsWith(expectedId));
	}
	
}