src/objects/BoomerangConfiguration__c.object
<CustomObject>
    <label>Boomerang Configuration</label>
    <nameField>
        <label>What does this step do?</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boomerang Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process__c.object
<CustomObject>
    <customHelpPage>ProcessHelp</customHelpPage>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sequence__c.object
<CustomObject>
    <customHelpPage>SequenceHelp</customHelpPage>
    <label>Sequence</label>
    <nameField>
        <label>Sequence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Step__c.object
<CustomObject>
    <fields>
        <fullName>ConfigurationId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>ConfigurationId</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipName>Steps</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Step</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BoomerangTest.cls
@isTest private class BoomerangTest {

    static testMethod void canDetermineConfigurable() {
        //arrange processes
        Process__c boomerangProcess = Processes.generateOne(Boomerang.class);
        
        //act
        String actualConfiguration = boomerangProcess.Configurable__c;
        
        //assert
        String expectedConfiguration = Schema.SobjectType.BoomerangConfiguration__c.Name;
        System.assertEquals(expectedConfiguration, actualConfiguration);
    }

    static testMethod void testMessageIsRedirected() {
        //arrange processes
        Process__c boomerangProcess = Processes.generateOne(Boomerang.class);
        Process__c terminateProcess = Processes.generateOne(Terminate.class);
        
        //arrange sequences
        Sequence__c origin = new Sequence__c(Name = 'originSequence');
        insert origin;
        Step__c originStep = Steps.generateOne(origin.Id, boomerangProcess.Id);
        
        Sequence__c target = new Sequence__c(Name = 'targetSequence');
        insert target;
        Step__c targetStep = Steps.generateOne(target.Id, terminateProcess.Id);
        
        //prepare configuration in db
        BoomerangConfiguration__c config = new BoomerangConfiguration__c(
            Id = originStep.ConfigurationId__c,
            Sequence__c = target.Id
        );
        update config;
        
        //prepare message
        Process.PluginRequest request = new Process.PluginRequest(new Map<String,Object>{
            'eda__sequenceName' => 'originSequence',
            'eda__position' => 1,
            'eda__configuration' => config.Id
        });
        
        //act
        Boomerang process = new Boomerang();
        Process.PluginResult result = process.invoke(request);
        List<Map<String,Object>> parametersList = Utility.convert(result);
        
        //asserts
        Decimal expectedSize = 1;
        Decimal actualSize = parametersList.size();
        System.assertEquals(expectedSize, actualSize);
        
        String expectedSequenceName = 'targetSequence';
        String actualSequenceName = (String)parametersList[0].get('eda__sequenceName');
        System.assertEquals(expectedSequenceName, actualSequenceName);
        
        Decimal expectedPosition = 0;
        Decimal actualPosition = (Decimal)parametersList[0].get('eda__position');
        System.assertEquals(expectedPosition, actualPosition);

        String expectedList = '["' + originStep.Id + '"]';
        String actualList = System.Json.serialize(parametersList[0].get('eda__boomerangStepIds'));
        System.assertEquals(expectedList, actualList);
    }
    
}