src/objects/BranchConfig__c.object
<CustomObject>
    <customHelpPage>BranchConfigHelp</customHelpPage>
    <fields>
        <fullName>Sequence__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>What sequence should messages be copied to?</inlineHelpText>
        <label>Sequence</label>
        <referenceTo>Sequence__c</referenceTo>
        <relationshipLabel>Branch Configs</relationshipLabel>
        <relationshipName>BranchConfigs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Branch Config</label>
    <nameField>
        <label>What does this step do?</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branch Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sequence__c.object
<CustomObject>
    <customHelpPage>SequenceHelp</customHelpPage>
    <label>Sequence</label>
    <nameField>
        <label>Sequence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Step__c.object
<CustomObject>
    <label>Step</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SequenceSetModelTest.cls
@IsTest private class SequenceSetModelTest {

    //before delete
    static testmethod void testDeleteTriggersAreCascaded() {
        //arrange sequence
        Sequence__c sequence = new Sequence__c(Name = 'testSequence');
        insert sequence;
        
        //arrange steps
        Step__c branchStep = SequenceModel.fromName(sequence.Name).appendStep(Branch.class);
        new StepModel(branchStep).upsertConfig();
        Step__c terminateStep = SequenceModel.fromName(sequence.Name).appendStep(Terminate.class);
        
        Integer expectedConfigsBefore = 1;
        Integer actualConfigsBefore = [SELECT COUNT() FROM BranchConfig__c];
        
        //act
        delete sequence;
        
        Integer expectedConfigsAfter = 0;
        Integer actualConfigsAfter = [SELECT COUNT() FROM BranchConfig__c];
        
        //assert
        System.assertEquals(expectedConfigsBefore, actualConfigsBefore);
        System.assertEquals(expectedConfigsAfter, actualConfigsAfter);
    }
    
    static testmethod void testMissingIdsDontAffectDelete() {
        //arrange sequence, steps, configs
        Sequence__c sequence = new Sequence__c(Name = 'Test');
        insert sequence;
        
        Step__c scheduleStep = SequenceModel.fromId(sequence.Id).appendStep(Schedule.class);
        Id configId = new stepModel(scheduleStep).upsertConfig();
        Step__c terminateStep = SequenceModel.fromId(sequence.Id).appendStep(Terminate.class);
        
        //act
        Database.delete(configId);
        delete sequence;
        
        Integer expectedCount = 0;
        Integer actualCount = [SELECT COUNT() FROM Step__c];
        System.assertEquals(expectedCount, actualCount, 'Wrong step count.');
    }

}