src/objects/BrokerSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Controls which broker implementation to use and whether it should run at all.</description>
    <fields>
        <fullName>BrokerClassName__c</fullName>
        <description>Fully qualified name of Broker subclass (eg esb_fb.FutureBroker)</description>
        <label>Broker Class Name</label>
        <length>97</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsPaused__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, this setting prevents new Messages from being processed. They will still enter the queue, but unresolved in a &apos;Queued&apos; status.</description>
        <label>IsPaused</label>
        <type>Checkbox</type>
    </fields>
    <label>Broker Settings</label>
</CustomObject>

src/objects/Message__c.object
<CustomObject>
    <customHelpPage>MessageHelp</customHelpPage>
    <label>Message</label>
    <nameField>
        <displayFormat>N-{0000000000}</displayFormat>
        <label>Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MessagePauseQueueExtensionTest.cls
@IsTest private class MessagePauseQueueExtensionTest {
    
    static testmethod void callingDoDmlCtorCorrectlySetsPauseFlag() {
        // arrange
        Boolean isPaused =  false;
        insert new BrokerSetting__c(BrokerClassName__c = SynchronousBroker.class.getName(), IsPaused__c = isPaused);
        
        //act - actions in the ctor
        MessagePauseQueueExtension.DoDml doDmlInstance = new MessagePauseQueueExtension.DoDml();
        
        //assemble
        BrokerSetting__c actualSettings  = BrokerSetting__c.getInstance();
        Boolean actualIsPaused =  actualSettings.IsPaused__c;

        // assert
        Boolean expectedIsPaused =  true;
        System.assertEquals( expectedIsPaused, actualIsPaused);
    }
    
    
   static testmethod void  callingDoPauseOnQueuedMessagesProcessesMessages() {
        // arrange
        Boolean isPaused =  false;
        insert new BrokerSetting__c(BrokerClassName__c = SynchronousBroker.class.getName(), IsPaused__c = isPaused);
        
        //act 
        ApexPages.StandardSetController controller = new ApexPages.StandardSetController([SELECT Id, Name FROM Message__c]);
        MessagePauseQueueExtension messagePauseQueueExtension =  new MessagePauseQueueExtension(controller);
        System.PageReference actualPageReference  = messagePauseQueueExtension.doPause();
        
        //assemble
        BrokerSetting__c actualSettings  = BrokerSetting__c.getInstance();
        Boolean actualIsPaused =  actualSettings.IsPaused__c;
        
        
        // assert
        Boolean expectedIsPaused =  (!isPaused);
        System.assertEquals( expectedIsPaused, actualIsPaused);
    }
}