src/objects/BrokerSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Controls which broker implementation to use and whether it should run at all.</description>
    <fields>
        <fullName>IsPaused__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, this setting prevents new Messages from being processed. They will still enter the queue, but unresolved in a &apos;Queued&apos; status.</description>
        <label>IsPaused</label>
        <type>Checkbox</type>
    </fields>
    <label>Broker Settings</label>
</CustomObject>

src/objects/Message__c.object
<CustomObject>
    <customHelpPage>MessageHelp</customHelpPage>
    <fields>
        <fullName>Sequence__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Which Sequence is this message progressing through?</inlineHelpText>
        <label>Sequence</label>
        <referenceTo>Sequence__c</referenceTo>
        <relationshipLabel>Messages</relationshipLabel>
        <relationshipName>Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>What stage of its lifecycle is this message at?</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Buffer</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reprocess</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Which Step is this message destined for?</inlineHelpText>
        <label>Step</label>
        <referenceTo>Step__c</referenceTo>
        <relationshipLabel>Messages</relationshipLabel>
        <relationshipName>Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Message</label>
    <nameField>
        <displayFormat>N-{0000000000}</displayFormat>
        <label>Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sequence__c.object
<CustomObject>
    <customHelpPage>SequenceHelp</customHelpPage>
    <label>Sequence</label>
    <nameField>
        <label>Sequence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Step__c.object
<CustomObject>
    <label>Step</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MessageResumeQueueExtensionTest.cls
@IsTest private class MessageResumeQueueExtensionTest {

    static testmethod void  callingDoDmlCtorCorrectlyResolvesFromQueuedToBufferedAndCorrectlySetsPause() {
        // arrange
        Boolean isPaused =  true;

        String sequenceNameA = 'sequenceA';
        Sequence__c sequenceA = new Sequence__c(Name = sequenceNameA);
        insert sequenceA;


        Integer positionA1 = 1;
        Integer positionA6 = 2;

        Step__c stepA1 = SequenceModel.fromName(sequenceA.Name).appendStep(Wiretap.class);
        Step__c stepA6 = SequenceModel.fromName(sequenceA.Name).appendStep(Terminate.class);

        //arrange specific broker implementation
        insert new BrokerSetting__c(IsPaused__c = isPaused);

        //tee up two messages in queued state
        new Job(sequenceNameA, '000000000000000AAA').persist();
        new Job(sequenceNameA, '000000000000000AAA').persist();
        
        //assert
        Integer expectedBefore = 2;
        Integer actualBefore = [SELECT COUNT() FROM Message__c WHERE Status__c = 'Paused'];
        System.assertEquals(expectedBefore, actualBefore, 'Wrong count before');
        
        //act - actions in the ctor
        MessageResumeQueueExtension.DoDml doDmlInstance = new MessageResumeQueueExtension.DoDml();

        //assemble
        Integer expectedAfter = 2;
        Integer actualAfter = [SELECT COUNT() FROM Message__c WHERE Status__c = 'Buffered'];
        System.assertEquals(expectedAfter, actualAfter, 'Wrong count after.');
    }

    static testmethod void  callingDoResumeOnQueuedMessagesEnqueuesWakeup() {
        // arrange
        Boolean isPaused =  true;

        String sequenceNameA = 'sequenceA';
        Sequence__c sequenceA = new Sequence__c(Name = sequenceNameA);
        insert sequenceA;


        Integer positionA1 = 1;
        Integer positionA6 = 2;

        Step__c stepA1 = SequenceModel.fromName(sequenceA.Name).appendStep(Wiretap.class);
        Step__c stepA6 = SequenceModel.fromName(sequenceA.Name).appendStep(Terminate.class);

        //arrange specific broker implementation
        insert new BrokerSetting__c(IsPaused__c = isPaused);

        //tee up two messages in queued state
        new Job(sequenceNameA, '000000000000000AAA').persist();
        new Job(sequenceNameA, '000000000000000AAA').persist();
        Broker.impl().run();

        //act -
        List<Message__c> messages = [SELECT Id FROM Message__c];
        ApexPages.StandardSetController controller = new ApexPages.StandardSetController(messages);
        MessageResumeQueueExtension messageResumeQueueExtension =  new MessageResumeQueueExtension(controller);
        System.PageReference actualPageReference  = messageResumeQueueExtension.doResume();

        // assert
        Integer expectedJobs = 1;
        Integer actualJobs = Limits.getQueueableJobs();
        System.assertEquals(expectedJobs, actualJobs, 'Wakeup not enqueued.');
    }
    
}