src/objects/BrokerSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Controls which broker implementation to use and whether it should run at all.</description>
    <label>Broker Settings</label>
</CustomObject>

src/objects/OAuthSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Holds the credentials needed to manage the Broker running user context. #774 formerly OAuth Setting</description>
    <fields>
        <fullName>AccessToken__c</fullName>
        <description>Roaring and ready access token that can be used to invoke Salesforce APIs.</description>
        <label>Access Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Setting</label>
</CustomObject>

src/classes/ApexClassListExtensionTest.cls
@IsTest class ApexClassListExtensionTest {
    
    static testmethod void testDoRedirect() {
        //act
        PageReference redirect = new ApexClassListExtension().doRedirect();
        
        //assert
        System.assertNotEquals(null, redirect, 'Wrong redirect.');
        
        //act (pretend to configure)
        OAuthSetting__c oauthSetting = OAuthSetting__c.getOrgDefaults();
        oauthSetting.AccessToken__c = '00D000000000000AAA';
        oauthSetting.UnprefixedOrgId__c = UserInfo.getOrganizationId().substring(3, 15);
        upsert oauthSetting;
        
        //act (pretend to discover)
        BrokerSetting__c brokerSetting = BrokerSetting__c.getOrgDefaults();
        brokerSetting.CacheKey__c = ApexClassSetModel.classKey();
        upsert brokerSetting;
        
        //act
        redirect = new ApexClassListExtension().doRedirect();
        
        //assert
        System.assertEquals(null, redirect, 'Wrong redirect.');
    }
    
}