src/objects/BrokerSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Powertrain control module</description>
    <fields>
        <fullName>BrokerClassName__c</fullName>
        <description>Fully qualified name of Broker subclass.</description>
        <label>Broker Class Name</label>
        <length>97</length>
        <type>Text</type>
    </fields>
    <label>Broker Settings</label>
</CustomObject>

src/classes/HeartbeatDispatcherTest.cls
@IsTest private class HeartbeatDispatcherTest {
    
    static testmethod void coverExecuteMethod() {
        //arrange specific broker implementation
        insert new BrokerSettings__c(BrokerClassName__c = SynchronousBroker.class.getName());
        
        //act
        Test.startTest();
        HeartbeatDispatcher dispatcher = new HeartbeatDispatcher();
        System.schedule('HeartbeatDispatcherTest', '0 0 * * * ?', dispatcher);
        //at 0 seconds
        //at 0 minutes
        //every hour
        //on every day of the month
        //on every month of the year
        //any day of the week
        //[optional year]
        dispatcher.execute(null);
        Test.stopTest();
        
        Integer expectedCount = 1;
        Integer actualCount = [SELECT COUNT() FROM AsyncApexJob WHERE ApexClass.Name = 'HeartbeatDispatcher'];
        System.assertEquals(expectedCount, actualCount);
    }
    
}