src/objects/BrokerSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Controls which broker implementation to use and whether it should run at all.</description>
    <label>Broker Settings</label>
</CustomObject>

src/objects/Sequence__c.object
<CustomObject>
    <customHelpPage>SequenceHelp</customHelpPage>
    <label>Sequence</label>
    <nameField>
        <label>Sequence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Step__c.object
<CustomObject>
    <fields>
        <fullName>Position__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Position</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Step</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Router.cls
/**
 * @obfuscation
 * Formerly known as Heartbeat
 */
public class Router extends ApexClassModel.Service {
    void callout(Map<String,Object> inputEvent) {}
    
    //#575 heartbeat evades discovery
    //public class Summary {}
    
    List<Map<String,Object>> execute(Map<String,Object> inputEvent) {
        
        //TODO do this dynamically
        Set<String> interestedSubscriberNames = new Set<String>{
            ScheduleDaily.class.getName()
        };
        
        List<Step__c> steps = [
            SELECT Id, Sequence__c, Position__c
            FROM Step__c
            WHERE ApexClassName__c IN :interestedSubscriberNames
        ];
        
        //stamp with version
        Integer version = Integer.valueOf(BrokerSetting__c.getOrgDefaults().Version__c);
        if (version == null) version = 1;
        integer position = 0;
        
        List<Map<String,Object>> outputEvents = new List<Map<String,Object>>();
        for (Step__c step : steps) outputEvents.add(new Map<String,Object>{
            'Route' => version + '#' + step.Sequence__c + '#' + position,
            'RecordId' => inputEvent.get('RecordId') //#971 this carries difference between heartbeat and test message
        });
        
        //destined for any schedule steps
        return outputEvents;
    }
    
}