src/objects/ChainStep__c.object
<CustomObject>
    <fields>
        <fullName>Process__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>ChainSteps</relationshipLabel>
        <relationshipName>ChainSteps</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>ChainStep</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ChainSteps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Process__c.object
<CustomObject>
    <customHelpPage>ProcessHelp</customHelpPage>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ChainStepExtensionConfigure.cls
public class ChainStepExtensionConfigure {
	
	private ChainStep__c chainStep;
	
	public ChainStepExtensionConfigure(ApexPages.StandardController controller) {
		controller.addFields(new List<String>{
			SObjectType.ChainStep__c.fields.Configuration__c.Name,
			SObjectType.ChainStep__c.fields.Process__c.Name
		});
		this.chainStep = (ChainStep__c)controller.getRecord();
	}
	
	public PageReference initConfig() {
		if (null == this.chainStep.Configuration__c) {
			//find process
			Process__c process = [SELECT ApexClass__c FROM Process__c WHERE Id = :chainStep.Process__c];
			
			//instantiate
			Type reflector = Type.forName(process.ApexClass__c);
			Configurable configurable = (Configurable)reflector.newInstance();
			
			//write configuration instance
			SObject configuration = (SObject)configurable.configure();
			insert configuration;
			
			//update chain step with id
			this.chainStep.Configuration__c = configuration.Id;
			update this.chainStep;
		}
		
		//return config
		return new PageReference('/' + this.chainStep.Configuration__c + '/e?retURL=' + chainStep.Id);
	}
	
}