src/objects/Chain__c.object
<CustomObject>
    <label>Chain</label>
    <nameField>
        <label>Chain Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process__c.object
<CustomObject>
    <customHelpPage>ProcessHelp</customHelpPage>
    <fields>
        <fullName>FullyQualifiedClassName__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>What is the underlying namespace prefix and Apex class name used by this process?</inlineHelpText>
        <label>Fully Qualified Class Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sequence__c.object
<CustomObject>
    <customHelpPage>SequenceHelp</customHelpPage>
    <label>Sequence</label>
    <nameField>
        <label>Sequence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Step__c.object
<CustomObject>
    <fields>
        <fullName>Chain__c</fullName>
        <label>Chain</label>
        <referenceTo>Chain__c</referenceTo>
        <relationshipName>Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ConfigurationId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>ConfigurationId</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ConfigurationName__c</fullName>
        <label>ConfigurationName</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipName>Steps</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Step</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Chain.cls
public class Chain extends SalesforceObject {

    public Chain(Chain__c chain) {
        super(chain);
    }
    
    public Steps fetchSteps() {
        List<String> fields = new List<String>();
        
        //step fields
        Set<String> stepFields = SObjectType.Step__c.Fields.getMap().keySet();
        for (String stepField : SObjectType.Step__c.Fields.getMap().keySet()) fields.add(stepField);
        
        //process fields
        Set<String> processFields = SObjectType.Process__c.Fields.getMap().keySet();
        for (String processField : SObjectType.Process__c.Fields.getMap().keySet()) fields.add(SObjectType.Step__c.Fields.Process__c.RelationshipName + '.' + processField);
        
        String chainId = this.getSObject().Id;
        String orderBy = SObjectType.Step__c.Fields.Sequence__c.Name;
        List<Step__c> steps = Database.query('SELECT ' + String.join(fields, ',') + ' FROM Step__c WHERE Chain__c = :chainId ORDER BY ' + orderBy);
        
        //ConfigurationName field from related configs
        for (Step__c step : steps) {
            Id configurationId = step.ConfigurationId__c;
            if (null == configurationId) continue;
            String objectType = configurationId.getSObjectType().getDescribe().getName();
            SObject config = Database.query('SELECT Id, Name FROM ' + objectType + ' WHERE Id = :configurationId');
            String configurationName = (String)config.get('Name');
            step.ConfigurationName__c = configurationName.left(80);
        }
        
        return new Steps(steps);
    }
    
    public Step appendStep(Id processId) {
        Step__c step = new Step__c(
            Chain__c = this.getSObject().Id,
            Process__c = processId
            //Sequence__c is automatic
        );
        
        insert step;
        return new Step(step);
    }
    
    /**
     * If this chain contains no Terminate step, append one.
     * (Invoked by the user interface when viewing a Chain for the first time)
     */
    public void terminate() {
        Chain__c chain = (Chain__c)this.getSObject();
        
        Process__c terminateProcess = [
            SELECT Id
            FROM Process__c
            WHERE FullyQualifiedClassName__c = :Terminate.class.getName()
        ];
        
        try {
            Step__c terminateStep = [
                SELECT Id
                FROM Step__c
                WHERE Chain__c = :chain.Id AND Process__c = :terminateProcess.Id
            ];
        } catch (QueryException e) {
            //chain contains no terminate step
            this.appendStep(terminateProcess.Id);
        }
    }
    
    public Step deleteStep(Id stepId) {
        //validate and perform the delete
        Chain__c chain = (Chain__c)this.getSObject();
        Step__c step = (Step__c)SalesforceObject.getById(stepId);
        System.assert(chain.Id == step.Chain__c, 'Cannot deleteStep from different chain ' + chain.Id + ' ' + step.Chain__c);
        delete step;
        
        //find the remaining steps
        List<Step__c> stepsToReorder = [
            SELECT Id
            FROM Step__c
            WHERE Chain__c = :chain.Id
            ORDER BY Sequence__c ASC
        ];
        
        //resequence them
        Integer sequence = 1;
        for (Step__c stepToReorder : stepsToReorder) stepToReorder.Sequence__c = sequence++;
        update stepsToReorder;
        
        //hand back wrapped deleted step
        return new Step(step);
    }

}