src/objects/ChainStep__c.object
<CustomObject>
    <fields>
        <fullName>ConfigurationId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Configuration</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>ChainStep</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ChainSteps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ConfigurationShowStepExtension.cls
public class ConfigurationShowStepExtension {
    
    private ApexPages.StandardController controller;
    
    public ConfigurationShowStepExtension(ApexPages.StandardController controller) {
        this.controller = controller;
    }
    
    /**
     * This resolves the Chain Step record for a given Configuration so that
     * it can be accessed from the native interface via a Custom Button.
     */
    public PageReference doRedirect() {
        ChainStep__c chainStep = [
            SELECT Id
            FROM ChainStep__c
            WHERE ConfigurationId__c = :(Id)this.controller.getId()
        ];
        return new ApexPages.StandardController(chainStep).view();
    }
    
}