src/objects/Chain__c.object
<CustomObject>
    <label>Chain</label>
    <nameField>
        <label>Chain Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ChainStep__c.object
<CustomObject>
    <fields>
        <fullName>Chain__c</fullName>
        <label>Chain</label>
        <referenceTo>Chain__c</referenceTo>
        <relationshipLabel>ChainSteps</relationshipLabel>
        <relationshipName>ChainSteps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>ChainSteps</relationshipLabel>
        <relationshipName>ChainSteps</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Sequence</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>ChainStep</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ChainSteps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Process__c.object
<CustomObject>
    <customHelpPage>ProcessHelp</customHelpPage>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ScrapeConfiguration__c.object
<CustomObject>
    <fields>
        <fullName>Endpoint__c</fullName>
        <label>Endpoint</label>
        <type>Url</type>
    </fields>
    <label>Scrape Configuration</label>
    <nameField>
        <label>What does this step do?</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scrape Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sequence__c.object
<CustomObject>
    <customHelpPage>SequenceHelp</customHelpPage>
    <label>Sequence</label>
    <nameField>
        <label>Sequence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ScrapeTest.cls
@isTest
public class ScrapeTest {
    
   private static string endPoint = 'http://a-site.com';
    
    
	public class MockHttpResponseGenerator implements HttpCalloutMock {
        // Implement this interface method
        public HTTPResponse respond(HTTPRequest req) {  
            String expectedEndpoint = endPoint;
            System.assertEquals(expectedEndpoint, req.getEndpoint());
            System.assertEquals('GET', req.getMethod());
            
            // Create a fake response
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('some content');
            res.setStatusCode(200);
            return res;
        }
    } 
    
    
    private static  testMethod void canDetermineConfigurable () {
        //arrange
        String  className  = 'Scrape';
        List<String> names = new List<String>{className};
        List<ApexClass> objects = [SELECT NamespacePrefix, Name FROM ApexClass WHERE Name IN :Names];
        ApexClasses apexClasses = new ApexClasses(objects);
        List<Process__c> processes = apexClasses.regenerate();
        
        //act
        String actualConfiguration = processes[0].Configurable__c;
        
        // Assert
        String expectedConfiguration = Schema.SobjectType.ScrapeConfiguration__c.Name;
        System.assertEquals(expectedConfiguration, actualConfiguration);  
    }
    
    private static  testMethod void callingInvokeCreatesExpectedAttachment() {
        //arrange
        String  className  = 'Scrape';
        List<String> names = new List<String>{className};
        List<ApexClass> objects = [SELECT NamespacePrefix, Name FROM ApexClass WHERE Name IN :Names];
        ApexClasses apexClasses = new ApexClasses(objects);
        List<Process__c> processes = apexClasses.regenerate();
       	Process__c scrapeProcess = processes[0];
        insert processes;

        Chain__c chain = new Chain__c(Name = 'ScrapeChain');
        insert chain;
        
        ChainStep__c chainStep = new ChainStep__c(Chain__c = chain.Id, Sequence__c = 2, Process__c = scrapeProcess.Id);
        insert chainStep;
        
        ScrapeConfiguration__c configuration = [
            SELECT Id, Endpoint__c
            FROM ScrapeConfiguration__c
        ];
        configuration.Endpoint__c = endPoint;
        update configuration;

        Map<String,Object> notification = new Map<String,Object>{'eda__configuration' => configuration.Id};

        //act
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        Test.startTest();
        Scrape plugin = new Scrape();
        Process.PluginResult result = plugin.invoke(new Process.PluginRequest(notification));
        List<Map<String,Object>> results = Utility.convert(result);
    	Test.stopTest();
        
       	// Assemble
        List<Attachment> attachments = [
            SELECT id, Name, ParentId, Body
            FROM Attachment 
            WHERE ParentId = :configuration.Id
        ];
        
        String actualBody = '';
        if (attachments.size() > 0) {
           actualBody = attachments[0].Body.toString();
        }

        // Assert
        String expectedBody = 'some content';
        System.assertEquals(expectedBody, actualBody);  
    }    
}