src/objects/Chain__c.object
<CustomObject>
    <label>Chain</label>
    <nameField>
        <label>Chain Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ChainStep__c.object
<CustomObject>
    <fields>
        <fullName>Chain__c</fullName>
        <label>Chain</label>
        <referenceTo>Chain__c</referenceTo>
        <relationshipLabel>ChainSteps</relationshipLabel>
        <relationshipName>ChainSteps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>ChainSteps</relationshipLabel>
        <relationshipName>ChainSteps</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Sequence</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>ChainStep</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ChainSteps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IsChangedConfiguration__c.object
<CustomObject>
    <fields>
        <fullName>FieldName__c</fullName>
        <label>FieldName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>IsChangedConfiguration</label>
    <nameField>
        <displayFormat>IC-{00000}</displayFormat>
        <label>IsChanged Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IsChanged Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process__c.object
<CustomObject>
    <customHelpPage>ProcessHelp</customHelpPage>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sequence__c.object
<CustomObject>
    <customHelpPage>SequenceHelp</customHelpPage>
    <label>Sequence</label>
    <nameField>
        <label>Sequence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/IsChangedTest.cls
@isTest
private class IsChangedTest {
  
    private static  testMethod void canDetermineConfigurable () {
        //arrange
        String  className  = 'IsChanged';
        List<String> names = new List<String>{className};
        List<ApexClass> objects = [SELECT NamespacePrefix, Name FROM ApexClass WHERE Name IN :Names];
        ApexClasses apexClasses = new ApexClasses(objects);
        List<Process__c> processes = apexClasses.regenerate();
        
        //act
        String actualConfiguration = processes[0].Configurable__c;
        
        // Assert
        String expectedConfiguration = Schema.SobjectType.IsChangedConfiguration__c.Name;
        System.assertEquals(expectedConfiguration, actualConfiguration);  
    }

    private static  testMethod void callingInvokeReturnsZeroNoticationsWhenNoChange() {
        //arrange
        String valueToHash = '12345' ;
        Blob value = Blob.valueOf( valueToHash );
        String hashedValue  = EncodingUtil.convertToHex(Crypto.generateDigest('MD5', value));
        Account account = new Account (Name = 'Crow' , Jigsaw = valueToHash );
        insert account;
        String accountId  = account.Id;
 
        String  className  = 'IsChanged';
        List<String> names = new List<String>{className};
        List<ApexClass> objects = [SELECT NamespacePrefix, Name FROM ApexClass WHERE Name IN :Names];
        ApexClasses apexClasses = new ApexClasses(objects);
        List<Process__c> processes = apexClasses.regenerate();
       	Process__c isChangedProcess = processes[0];
        insert processes;

        Chain__c chain = new Chain__c(Name = 'IsChangedChain');
        insert chain;
        
        ChainStep__c chainStep = new ChainStep__c(Chain__c = chain.Id, Sequence__c = 2, Process__c = isChangedProcess.Id);
        insert chainStep;


        IsChangedConfiguration__c configuration = [
            SELECT Id, FieldName__c, LastHash__c 
            FROM IsChangedConfiguration__c
        ];
        configuration.FieldName__c = 'Jigsaw';
        configuration.LastHash__c = hashedValue;
        update configuration;
        
        Map<String,Object> notification = new Map<String,Object>{
            'eda__configuration' => [SELECT id FROM IsChangedConfiguration__c].Id,
            'id' => accountId
        };

        //act
        IsChanged plugin = new IsChanged();
        Process.PluginResult result = plugin.invoke(new Process.PluginRequest(notification));
        List<Map<String,Object>> results = Utility.convert(result);

        // Assert
        Integer expectedSize = 0;  //-- same value , so expect zer0 
        Integer actualSize = results.size();     
        System.assertEquals(expectedSize, actualSize);  
    }  


    private static  testMethod void callingInvokeReturnsOneNoticationWhenThereIsAChange() {
        //arrange
        String valueToHash = '12345' ;
        String newValue    = '67890' ;
        Blob value = Blob.valueOf( valueToHash );
        String hashedValue  = EncodingUtil.convertToHex(Crypto.generateDigest('MD5', value));
        Account account = new Account (Name = 'Crow' , Jigsaw = newValue);
        insert account;
        String accountId  = account.Id;
 
        String  className  = 'IsChanged';
        List<String> names = new List<String>{className};
        List<ApexClass> objects = [SELECT NamespacePrefix, Name FROM ApexClass WHERE Name IN :Names];
        ApexClasses apexClasses = new ApexClasses(objects);
        List<Process__c> processes = apexClasses.regenerate();
       	Process__c isChangedProcess = processes[0];
        insert processes;

        Chain__c chain = new Chain__c(Name = 'IsChangedChain');
        insert chain;
        
        ChainStep__c chainStep = new ChainStep__c(Chain__c = chain.Id, Sequence__c = 2, Process__c = isChangedProcess.Id);
        insert chainStep;

        IsChangedConfiguration__c configuration = [
            SELECT Id, FieldName__c, LastHash__c 
            FROM IsChangedConfiguration__c
        ];
        configuration.FieldName__c = 'Jigsaw';
        configuration.LastHash__c = hashedValue;
        update configuration;
        
        Map<String,Object> notification = new Map<String,Object>{
            'eda__configuration' => [SELECT id FROM IsChangedConfiguration__c].Id,
            'id' => accountId
        };

        //act
        IsChanged plugin = new IsChanged();
        Process.PluginResult result = plugin.invoke(new Process.PluginRequest(notification));
        List<Map<String,Object>> results = Utility.convert(result);
 
        // Assert
        Integer expectedSize = 1;       //-- new value , so expect one 
        Integer actualSize = results.size();     
        System.assertEquals(expectedSize, actualSize);  
    }  
    
    
}