src/objects/Chain__c.object
<CustomObject>
    <label>Chain</label>
    <nameField>
        <label>Chain Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ChainStep__c.object
<CustomObject>
    <fields>
        <fullName>Chain__c</fullName>
        <label>Chain</label>
        <referenceTo>Chain__c</referenceTo>
        <relationshipLabel>ChainSteps</relationshipLabel>
        <relationshipName>ChainSteps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ConfigurationId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Configuration</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>ChainSteps</relationshipLabel>
        <relationshipName>ChainSteps</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>ChainStep</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ChainSteps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Process__c.object
<CustomObject>
    <customHelpPage>ProcessHelp</customHelpPage>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ChainStepExtensionConfigureTest.cls
@isTest  //-- no view of org data
private  class ChainStepExtensionConfigureTest {
    static testMethod void callingInitConfigWhenConfigurationIdNotNullReturnsExpectedUrl() {
        //arrange processes
        Process__c branchProcess = Processes.generateOne(Branch.class);
        
        //arrange chain
        Chain__c chain = new Chain__c( Name = 'the-chain');
        insert chain;
        
        //arrange steps
        ChainStep__c chainStep = ChainSteps.generateOne(chain.Id, branchProcess.Id);

        String expectedPageReferenceUrl = new PageReference('/' + chainStep.ConfigurationId__c + '/e?retURL=' + chainStep.Id).getUrl();

        // Act
        ApexPages.StandardController controller = new ApexPages.StandardController(chainStep);
        ChainStepExtensionConfigure chainStepExtensionConfigure = new ChainStepExtensionConfigure( controller );
        String actualPageReferenceUrl = chainStepExtensionConfigure.initConfig().getUrl();

        // Assert
        System.assertEquals(expectedPageReferenceUrl , actualPageReferenceUrl );
        /////// expectedPageReferenceUrl=[ /null/e?retURL=a02b0000008Ewn5AAC ], actualPageReferenceUrl=[ /a02b0000008Ewn5 ]
    }

    static testMethod void callingInitConfigWhenConfigurationIdIsNullReturnsExpectedUrl() {
        //arrange processes
        Process__c branchProcess = Processes.generateOne(Branch.class);
        
        //arrange chain
        Chain__c chain = new Chain__c(Name = 'the-chain');
        insert chain;

        //arrange steps
        ChainStep__c chainStep = ChainSteps.generateOne(chain.Id, branchProcess.Id);

        boolean expectedPageReferenceUrlFlag = true;

        // Act
        ApexPages.StandardController controller = new ApexPages.StandardController(chainStep);
        ChainStepExtensionConfigure chainStepExtensionConfigure = new ChainStepExtensionConfigure( controller );
        
        // Prepare
        String actualUrl = chainStepExtensionConfigure.initConfig().getUrl();
        String expectedUrl = String.valueOf(chainStep.Id).left(15);

        // Assert
        System.assert(actualUrl.contains(expectedUrl));
    }
}