src/objects/Chain__c.object
<CustomObject>
    <label>Chain</label>
    <nameField>
        <label>Chain Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ChainStep__c.object
<CustomObject>
    <fields>
        <fullName>Chain__c</fullName>
        <label>Chain</label>
        <referenceTo>Chain__c</referenceTo>
        <relationshipLabel>ChainSteps</relationshipLabel>
        <relationshipName>ChainSteps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ChainStep</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ChainSteps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Chains.cls
public class Chains extends SObjects {

	/**
	 * When deleting a MASTER, Salesforce does not fire the DETAIL delete triggers.
	 * https://success.salesforce.com/ideaView?id=08730000000BqSJ
	 * So we cascade the delete ourselves manually, to make sure they fire.
	 */
	public override void onBeforeDelete(Map<Id,SObject> objects) {
		Set<Id> chainIds = objects.keySet();
		
		List<ChainStep__c> chainSteps = [
			SELECT Id
			FROM ChainStep__c
			WHERE Chain__c IN :chainIds
		];
		
		delete chainSteps; 
	}
}