src/objects/ConfirmItem__c.object
<CustomObject>
    <customHelpPage>ConfirmItemCsh</customHelpPage>
    <fields>
        <fullName>Confirm__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confirm</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DenySequence__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What sequence to jump to if denied?</inlineHelpText>
        <label>Deny Sequence</label>
        <referenceTo>Sequence__c</referenceTo>
        <relationshipLabel>Confirm Items</relationshipLabel>
        <relationshipName>ConfirmItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deny__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Deny</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parameters__c</fullName>
        <label>Parameters</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Confirm Item</label>
    <nameField>
        <label>Confirm Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Confirm Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Message__c.object
<CustomObject>
    <customHelpPage>MessageHelp</customHelpPage>
    <fields>
        <fullName>Parameters__c</fullName>
        <inlineHelpText>What is the JSON object representing the parameters carried by this message?</inlineHelpText>
        <label>Parameters</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Which Sequence is this message progressing through?</inlineHelpText>
        <label>Sequence</label>
        <referenceTo>Sequence__c</referenceTo>
        <relationshipLabel>Messages</relationshipLabel>
        <relationshipName>Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>What stage of its lifecycle is this message at?</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Buffer</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reprocess</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Message</label>
    <nameField>
        <displayFormat>N-{0000000000}</displayFormat>
        <label>Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sequence__c.object
<CustomObject>
    <customHelpPage>SequenceHelp</customHelpPage>
    <label>Sequence</label>
    <nameField>
        <label>Sequence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ConfirmItemObjectSet.cls
public with sharing class ConfirmItemObjectSet extends SalesforceObjectSet {
    
    public ConfirmItemObjectSet(List<ConfirmItem__c> confirmItems) {
        super(confirmItems);
    }
    
    override public void onAfterUpdate(List<SObject> oldObjects) {
        this.handleConfirms();
        this.handleDenies();
    }
    
    @TestVisible private void handleConfirms() {
        List<Message__c> messages = new List<Message__c>();
        List<ConfirmItem__c> confirmItems = this.getSObjects();
        List<Id> idsToDelete = new List<Id>();
        
        //these guys carry on to next step
        for (ConfirmItem__c confirmItem : confirmItems) {
            if (!confirmItem.Confirm__c) continue; //nothing to do
            
            Map<String,Object> parameters = (Map<String,Object>)Json.deserializeUntyped(confirmItem.Parameters__c);
            parameters.put('esb__Confirm', true);
            messages.add(new Message__c(
                Status__c = 'Buffered',
                Parameters__c = Json.serializePretty(parameters)
            ));
            
            idsToDelete.add(confirmItem.Id);
        }
        
        insert messages; //note they will start mid sequence
        Job.process();
        
        Database.delete(idsToDelete);
    }
    
    @TestVisible private void handleDenies() {
        List<Message__c> messages = new List<Message__c>();
        List<ConfirmItem__c> confirmItems = this.getSObjects();
        List<Id> idsToDelete = new List<Id>();
        
        //these guys have no deny sequence and go to hell
        for (ConfirmItem__c confirmItem : confirmItems) {
            if (!confirmItem.Deny__c) continue; //nothing to do
            if (confirmItem.DenySequence__c != null) continue; //nothing to do
            idsToDelete.add(confirmItem.Id);
        }
        
        //gotta get the sequence names
        List<Id> denySequenceIds = new List<Id>();
        for (ConfirmItem__c confirmItem : confirmItems) denySequenceIds.add(confirmItem.DenySequence__c);
        Map<Id,Sequence__c> id2sequence = new Map<Id,Sequence__c>([SELECT Id, Name FROM Sequence__c WHERE Id IN :denySequenceIds]);
        
        //these guys have a deny sequence and sent straight there
        for (ConfirmItem__c confirmItem : confirmItems) {
            if (!confirmItem.Deny__c) continue; //nothing to do
            if (confirmItem.DenySequence__c == null) continue; //nothing to do
            
            Map<String,Object> parameters = (Map<String,Object>)Json.deserializeUntyped(confirmItem.Parameters__c);
            parameters.put('esb__Deny', true);
            parameters.put('__SequenceName', id2sequence.get(confirmItem.DenySequence__c).Name);
            parameters.put('__Position', 0);
            messages.add(new Message__c(
                Status__c = 'Buffered',
                Parameters__c = Json.serializePretty(parameters)
            ));
            
            idsToDelete.add(confirmItem.Id);
        }
        
        insert messages; //new guys start mid sequence
        Job.process();
        
        Database.delete(idsToDelete);
    }
    
}