src/objects/ConfirmConfig__c.object
<CustomObject>
    <customHelpPage>ConfirmConfigCsh</customHelpPage>
    <label>Confirm Config</label>
    <nameField>
        <label>Confirm Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Confirm Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ConfirmItem__c.object
<CustomObject>
    <customHelpPage>ConfirmItemCsh</customHelpPage>
    <fields>
        <fullName>ConfirmConfig__c</fullName>
        <label>Confirm Config</label>
        <referenceTo>ConfirmConfig__c</referenceTo>
        <relationshipLabel>Confirm Items</relationshipLabel>
        <relationshipName>ConfirmItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Deny__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Deny</label>
        <type>Checkbox</type>
    </fields>
    <label>Confirm Item</label>
    <nameField>
        <label>Confirm Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Confirm Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ConfirmItemDenyExtension.cls
public with sharing class ConfirmItemDenyExtension {
    
    private ApexPages.StandardController controller;
    
    public ConfirmItemDenyExtension(ApexPages.StandardController controller) {
        this.controller = controller;
    }
    
    public PageReference doDeny() {
        Id confirmItemId = controller.getId();
        ConfirmItem__c confirmItem = (ConfirmItem__c)SalesforceObject.getById(confirmItemId);
        
        confirmItem.Deny__c = true;
        update confirmItem;
        
        ConfirmConfig__c confirmConfig = new ConfirmConfig__c(Id = confirmItem.ConfirmConfig__c);
        return new ApexPages.StandardController(confirmConfig).view();
    }

}