src/objects/ConfirmConfig__c.object
<CustomObject>
    <customHelpPage>ConfirmConfigCsh</customHelpPage>
    <fields>
        <fullName>DenySequence__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What sequence to jump to if denied?</inlineHelpText>
        <label>Deny Sequence</label>
        <referenceTo>Sequence__c</referenceTo>
        <relationshipLabel>Confirm Configs</relationshipLabel>
        <relationshipName>ConfirmConfigs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Confirm Config</label>
    <nameField>
        <label>Confirm Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Confirm Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ConfirmItem__c.object
<CustomObject>
    <customHelpPage>ConfirmItemCsh</customHelpPage>
    <fields>
        <fullName>ConfirmConfig__c</fullName>
        <label>Confirm Config</label>
        <referenceTo>ConfirmConfig__c</referenceTo>
        <relationshipLabel>Confirm Items</relationshipLabel>
        <relationshipName>ConfirmItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DenySequence__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What sequence to jump to if denied?</inlineHelpText>
        <label>Deny Sequence</label>
        <referenceTo>Sequence__c</referenceTo>
        <relationshipLabel>Confirm Items</relationshipLabel>
        <relationshipName>ConfirmItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EntityId__c</fullName>
        <externalId>true</externalId>
        <label>EntityId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parameters__c</fullName>
        <label>Parameters</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Confirm Item</label>
    <nameField>
        <label>Confirm Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Confirm Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Confirm.cls
public with sharing class Confirm {
    
    public ConfirmConfig__c StepConfig;
    public String Parameters;
    
    public class Meta {
        public String Tag = 'Enterprise Service Bus';
        public String Name = 'Confirm';
        public String Icon = 'control_pause_blue';
        public String Description = 'Captures messages and requires them to be confirmed in order to continue.';
        public SObject StepConfig = ConfirmConfig__c.SObjectType.newSObject();
        public String HelpUrl = Page.ConfirmConfigCsh.getUrl();
    }
    
    override public String toString() {
        Map<String,Object> parameters = (Map<String,Object>)Json.deserializeUntyped(this.Parameters);
        
        //save away (can be resumed later)
        insert new ConfirmItem__c(
            EntityId__c = (Id)parameters.get('esb__Id'),
            Parameters__c = Json.serializePretty(parameters),
            DenySequence__c = this.StepConfig.DenySequence__c,
            ConfirmConfig__c = this.StepConfig.Id
        );
        
        //swallow
        return '[]';
    }

}