src/objects/Debouncer__c.object
<CustomObject>
    <fields>
        <fullName>DebouncerConfiguration__c</fullName>
        <label>Debouncer Configuration</label>
        <referenceTo>DebouncerConfiguration__c</referenceTo>
        <relationshipLabel>Debouncers</relationshipLabel>
        <relationshipName>Debouncers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastFiredDate__c</fullName>
        <label>Last Fired Date</label>
        <type>DateTime</type>
    </fields>
    <label>Debouncer</label>
    <nameField>
        <displayFormat>D-{0000000000}</displayFormat>
        <label>Debouncer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debouncers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DebouncerConfiguration__c.object
<CustomObject>
    <fields>
        <fullName>MinimumHoursBetween__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Minimum Hours Between</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Debouncer Configuration</label>
    <nameField>
        <label>What does this step do?</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Debouncer Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Debouncer.cls
public class Debouncer implements Process.Plugin {
    
    public class DebouncerException extends Exception {}
    
    public class Meta {
        public SObject ConfigObject = DebouncerConfiguration__c.SObjectType.newSobject();
        public String Icon = 'key_go';
    }
    
    public Process.PluginDescribeResult describe() {
        Process.PluginDescribeResult result = new Process.PluginDescribeResult();
        result.Tag = 'Event Driven Architecture';
        result.Name = 'Debouncer';
        result.Description = 'Swallows message unless the time elapsed since receiving a prior notification with the same key exceeds a min threshold';
        return result;
    }
    
    public Process.PluginResult invoke(Process.PluginRequest pluginRequest) {
        Map<String,Object> parameters = pluginRequest.inputParameters;
        List<Map<String,Object>> parametersList = new List<Map<String,Object>>();
        
        String key = (String) parameters.get('Id'); //Note we sill treat null as a unique key with value [null]
        Id configurationId = (Id)parameters.get('eda_ConfigObjectId');
        
        if (configurationId == null) {
            throw new DebouncerException('Cannot invoke debouncer with null parameters[eda_configuration]');
        }
        
        // retrieve minimum time between releases
        DebouncerConfiguration__c configuration = [
        SELECT Id, MinimumHoursBetween__c
            FROM DebouncerConfiguration__c
            WHERE Id = :configurationId
        ];
        Integer minimumHours = (configuration.MinimumHoursBetween__c == null) ? 0 : (Integer)configuration.MinimumHoursBetween__c;
        
        // retrieve debouncer (if any)
        List<Debouncer__c> debouncers = [
            SELECT Id, LastFiredDate__c, Key__c
            FROM Debouncer__c
            WHERE DebouncerConfiguration__c = :configurationId
            AND Key__c = :key
        ];
        
        DateTime currentStamp = System.now();
        Boolean release = debounce( currentStamp, key, minimumHours, debouncers , configurationId );
        if (release) {
            parametersList.add(parameters);
        }

        // housekeeping
        Integer twentyFourHours = 24;
        deleteOldDebouncers(currentStamp, minimumHours, twentyFourHours) ;
        
        return EdaUtility.convert(parametersList);
    }
    
    @testVisible
    private static Boolean debounce(
        DateTime currentStamp,
        String key,
        Integer minimumHours,
        List<Debouncer__c> debouncers,
        Id debouncerConfigurationId
    ) {
        // normalize
        Debouncer__c debouncer;
        Boolean keyInstance = (debouncers.size() > 0);
        if (!keyInstance) {
            debouncer = new Debouncer__c (
                DebouncerConfiguration__c = debouncerConfigurationId,
                LastFiredDate__c = null,
                Key__c = key
            );
            insert debouncer;
        } else {
            debouncer = debouncers[0];
        }
    
    
        // decision and potential release
        Boolean release = ( ! keyInstance );
        if (!release) {
            DateTime cutOff = currentStamp.addHours(-1 * minimumHours);
            release = debouncers[0].LastFiredDate__c < cutOff;
        }
        
        // persist state
        if (release) {
            debouncer.LastFiredDate__c = currentStamp;
            update debouncer;
        }
        
        return release;
    }
    
    
    
    @testVisible
    private static void deleteOldDebouncers(
        DateTime currentStamp,
        Integer minimumHours,
        Integer bufferHours
    ) {
    
        DateTime staleStamp = currentStamp.AddHours( -1 * ( bufferHours + minimumHours) ) ;
        List<Id> ids = new List<Id> (
        new Map<Id, Debouncer__c>([
            SELECT Id
            FROM Debouncer__c
            WHERE LastFiredDate__c < :staleStamp
        ]).keySet());
        
        if (ids.size() > 0) {
            Database.delete(ids);
            Database.emptyRecycleBin(ids);
        }
    }
}