src/objects/DisperseConfig__c.object
<CustomObject>
    <customHelpPage>DisperseConfigCsh</customHelpPage>
    <label>Disperse Config</label>
    <nameField>
        <label>What does this step do?</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Disperse Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DisperseDestination__c.object
<CustomObject>
    <customHelpPage>DisperseDestinationCsh</customHelpPage>
    <fields>
        <fullName>DisperseConfig__c</fullName>
        <label>Disperse Config</label>
        <referenceTo>DisperseConfig__c</referenceTo>
        <relationshipName>DisperseDestinations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Point and click flow control.</description>
        <inlineHelpText>What sequence(s) should messages be copied to?</inlineHelpText>
        <label>Sequence</label>
        <referenceTo>Sequence__c</referenceTo>
        <relationshipName>DisperseDestinations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Disperse Destination</label>
    <nameField>
        <label>Destination Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Disperse Destinations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sequence__c.object
<CustomObject>
    <customHelpPage>SequenceHelp</customHelpPage>
    <label>Sequence</label>
    <nameField>
        <label>Sequence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Step__c.object
<CustomObject>
    <label>Step</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DisperseTest.cls
@IsTest public class DisperseTest {
    
    static testmethod void testDisperseSendsMultipleMessages() {
        //arrange sequences
        Sequence__c sequence1 = new Sequence__c(Name = 'Test1');
        insert sequence1;
        Step__c step1 = SequenceModel.fromName(sequence1.Name).appendStep(Terminate.class.getName());
        
        Sequence__c sequence2 = new Sequence__c(Name = 'Test2');
        insert sequence2;
        Step__c step2 = SequenceModel.fromName(sequence2.Name).appendStep(Terminate.class.getName());
        
        Sequence__c sequence3 = new Sequence__c(Name = 'Test3');
        insert sequence3;
        Step__c step3 = SequenceModel.fromName(sequence3.Name).appendStep(Terminate.class.getName());
        
        //arrange disperser
        DisperseConfig__c config = new DisperseConfig__c();
        insert config;
        insert new DisperseDestination__c(DisperseConfig__c = config.Id, Sequence__c = sequence1.Id);
        insert new DisperseDestination__c(DisperseConfig__c = config.Id, Sequence__c = sequence2.Id);
        insert new DisperseDestination__c(DisperseConfig__c = config.Id, Sequence__c = sequence3.Id);
        
        //arrange invocation
        Disperse process = new Disperse();
        process.Event = Json.serialize(new Map<String,Object>{
            'esb__StepConfig' => config
        });
        
        //act
        String outputs = process.toString();
        
        //assemble
        List<Object> events = (List<Object>)Json.deserializeUntyped(outputs);
        
        //assert
        Integer expectedOutputs = 3;
        Integer actualOutputs = events.size();
        System.assertEquals(expectedOutputs, actualOutputs, 'Wrong number of outputs.');
    }
    
    static testmethod void testDisperseDumbConfig() {
        //arrange sequences
        Sequence__c sequence = new Sequence__c(Name = 'Test');
        insert sequence;
        Step__c step1 = SequenceModel.fromName(sequence.Name).appendStep(Terminate.class.getName());
        
        //arrange disperser
        DisperseConfig__c config = new DisperseConfig__c();
        insert config;
        insert new DisperseDestination__c(DisperseConfig__c = config.Id, Sequence__c = sequence.Id);
        
        //arrange invocation
        Disperse process = new Disperse();
        process.Event = Json.serialize(new Map<String,Object>{
            'esb__StepConfig' => config,
            '__SequenceName' => 'Test'
        });
        
        //act
        try {
            String outputs = process.toString();
            System.assert(false, '');
        } catch (Disperse.DisperseException e) {
            String expectedMessage = 'Disperse cannot include its own Sequence as a Destination.';
            String actualMessage = e.getMessage();
            System.assertEquals(expectedMessage, actualMessage, 'Wrong exception.');
        }
    }
    
}