src/objects/EventType__c.object
<CustomObject>
    <customHelpPage>EventTypeCsh</customHelpPage>
    <label>Event Type</label>
    <nameField>
        <label>Event Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PublishConfig__c.object
<CustomObject>
    <customHelpPage>PublishConfigCsh</customHelpPage>
    <fields>
        <fullName>EventType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>What event type should this step broadcast messages to?</inlineHelpText>
        <label>Event Type</label>
        <referenceTo>EventType__c</referenceTo>
        <relationshipLabel>Publish Configs</relationshipLabel>
        <relationshipName>PublishConfigs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publish Config</label>
    <nameField>
        <label>What does this step do?</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publish Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Step__c.object
<CustomObject>
    <label>Step</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SubscribeConfig__c.object
<CustomObject>
    <fields>
        <fullName>EventType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>What event type should this step listen to messages from?</inlineHelpText>
        <label>Event Type</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>You may select a Simple Event only.</errorMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>EventType__c</referenceTo>
        <relationshipLabel>Subscribe Configs</relationshipLabel>
        <relationshipName>SubscribeConfigs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscribe Config</label>
    <nameField>
        <label>What does this step do?</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscribe Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Publish.cls
public class Publish extends ApexClassModel.BaseProcess {
    
    /**
     * @docs ProcessPublishSubscribe.html
     */
    public class ESB extends ApexClassModel.BaseSummary {
        String Tag = 'Enterprise Service Bus';
        String Name = 'Publish';
        String Description = 'Broadcasts the message to other sequences via a named Event Type.';
        String StepConfig = PublishConfig__c.class.getName();
        String Icon = 'chart_organisation';
        String HelpUrl = new PageReference('/apex/ContextSensitiveHelp?topic=ProcessPublishSubscribe').getUrl();
        Integer Limits = 33; //max sync limit
        String Cardinality = 'One';
    }
    
    public class PublishException extends Exception {}

    List<Map<String,Object>> execute(Map<String,Object> inputEvent) {
        
        String stepConfigId = (Id)inputEvent.get('StepConfigId');
        if (stepConfigId == null) throw new PublishException('Null step config id.');
        
        PublishConfig__c publishConfig = [
            SELECT EventType__c
            FROM PublishConfig__c
            WHERE Id = :stepConfigId
        ];
        
        Id eventTypeId = publishConfig.EventType__c;
        if (eventTypeId == null) throw new PublishException('No event type.');
        
        List<SubscribeConfig__c> subscribeConfigs = [
            SELECT Id
            FROM SubscribeConfig__c
            WHERE EventType__c = :eventTypeId
        ];
        
        List<Step__c> steps = [
            SELECT SequenceName__c
            FROM Step__c
            WHERE ConfigId__c IN :new Map<Id,SObject>(subscribeConfigs).keySet()
        ];
        
        List<Map<String,Object>> outputEvents = new List<Map<String,Object>>();
        for (Step__c step : steps) outputEvents.add(new Map<String,Object>{
            'Sequence' => step.SequenceName__c
        });
        
        //#994 re-use enqueue logic to do pre-routing
        outputEvents = new Job(outputEvents).Events;
        
        //original guy carries on... this does not inadvertently Terminate
        outputEvents.add(inputEvent);
        
        return outputEvents;
    }
}