src/objects/EventType__c.object
<CustomObject>
    <customHelpPage>EventTypeCsh</customHelpPage>
    <label>Event Type</label>
    <nameField>
        <label>Event Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process__c.object
<CustomObject>
    <customHelpPage>ProcessHelp</customHelpPage>
    <fields>
        <fullName>FullyQualifiedClassName__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>What is the underlying namespace prefix and Apex class name used by this process?</inlineHelpText>
        <label>Fully Qualified Class Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PublishConfiguration__c.object
<CustomObject>
    <fields>
        <fullName>EventType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Event Type</label>
        <referenceTo>EventType__c</referenceTo>
        <relationshipLabel>Publish Configurations</relationshipLabel>
        <relationshipName>PublishConfigurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publish Configuration</label>
    <nameField>
        <label>What does this step do?</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publish Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sequence__c.object
<CustomObject>
    <customHelpPage>SequenceHelp</customHelpPage>
    <label>Sequence</label>
    <nameField>
        <label>Sequence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Step__c.object
<CustomObject>
    <fields>
        <fullName>ConfigurationId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>ConfigurationId</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Position</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipName>Steps</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Step</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SubscribeConfiguration__c.object
<CustomObject>
    <fields>
        <fullName>EventType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Event Type</label>
        <referenceTo>EventType__c</referenceTo>
        <relationshipLabel>Subscribe Configurations</relationshipLabel>
        <relationshipName>SubscribeConfigurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscribe Configuration</label>
    <nameField>
        <label>What does this step do?</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscribe Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SubscribeHelpController.cls
public with sharing class SubscribeHelpController {
    
    public void findProblems() {
        
        List<Sequence__c> sequences = [
            SELECT Id, Name,
            (SELECT Id, Name, Process__c, ConfigurationId__c FROM Steps__r ORDER BY Position__c ASC) steps
            FROM Sequence__c
            LIMIT 10000 //resolves checkmarx Queries_With_No_Where_Or_Limit_Clause
        ];
        
        Process__c subscribeProcess = [
            SELECT Id
            FROM Process__c
            WHERE FullyQualifiedClassName__c = :Subscribe.class.getName()
        ];
        
        Map<Id,SObject> subscribeConfigurationIdToSubscribeConfiguration = SalesforceObjectSet.mapAll(SubscribeConfiguration__c.SObjectType);
        List<PublishConfiguration__c> publishConfigurations = SalesforceObjectSet.listAll(PublishConfiguration__c.SObjectType);
        Map<Id,SObject> eventTypeIdToEventType = SalesforceObjectSet.mapAll(EventType__c.SObjectType);
        
        for (Sequence__c sequence : sequences) {
            List<Step__c> steps = sequence.Steps__r;
            Integer subscribeOccurs = 0;
            Integer count = 1;
            Boolean subscribeFirst = false;
            Id stepId = null;
            Id subscribeConfigurationId = null;
            
            for (Step__c step : steps) {
                if (step.Process__c == SubscribeProcess.Id) {
                    subscribeOccurs++;
                    subscribeConfigurationId = (Id) step.ConfigurationId__c; // cast from string to Id
                    if (count == 1) {
                        subscribeFirst = true;
                        stepId = step.Id;
                    }
                }
                count++;
            }
            
            //this sequence has no subscribe step
            if (subscribeOccurs == 0) continue;
            
            if (!subscribeFirst) {
                ApexPages.addMessage(new ApexPages.Message(
                    ApexPages.Severity.WARNING,
                    'Subscribe process not first step of sequence ' + sequence.Id
                ));
                continue;
            }
            
            if (subscribeOccurs > 1) {
                ApexPages.addMessage(new ApexPages.Message(
                    ApexPages.Severity.WARNING,
                    'Subscribe appears more than once in sequence ' + sequence.Id
                ));
                continue;
            }
            
            SubscribeConfiguration__c subscribeConfiguration = (SubscribeConfiguration__c)subscribeConfigurationIdToSubscribeConfiguration.get(subscribeConfigurationId);
            if (subscribeConfiguration.EventType__c == null) {
                ApexPages.addMessage(new ApexPages.Message(
                    ApexPages.Severity.WARNING,
                    'No event type defined on Subscribe Configuration ' + sequence.Id
                ));
                continue;
            }
            
            Boolean publisherFound = false;
            for (PublishConfiguration__c  publishConfiguration : publishConfigurations) {
                if (subscribeConfiguration.EventType__c != null && publishConfiguration.EventType__c == subscribeConfiguration.EventType__c) publisherFound = true;
            }
            
            if (!publisherFound) {
                ApexPages.addMessage(new ApexPages.Message(
                    ApexPages.Severity.WARNING,
                    'No publisher is configured to publish event ' + sequence.Id
                ));
                continue;
            }
        }
    }

}