src/objects/EventType__c.object
<CustomObject>
    <customHelpPage>EventTypeCsh</customHelpPage>
    <label>Event Type</label>
    <nameField>
        <label>Event Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process__c.object
<CustomObject>
    <customHelpPage>ProcessHelp</customHelpPage>
    <fields>
        <fullName>FullyQualifiedClassName__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>What is the underlying namespace prefix and Apex class name used by this process?</inlineHelpText>
        <label>Fully Qualified Class Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PublishConfiguration__c.object
<CustomObject>
    <fields>
        <fullName>EventType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Event Type</label>
        <referenceTo>EventType__c</referenceTo>
        <relationshipLabel>Publish Configurations</relationshipLabel>
        <relationshipName>PublishConfigurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publish Configuration</label>
    <nameField>
        <label>What does this step do?</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publish Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sequence__c.object
<CustomObject>
    <customHelpPage>SequenceHelp</customHelpPage>
    <label>Sequence</label>
    <nameField>
        <label>Sequence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Step__c.object
<CustomObject>
    <fields>
        <fullName>ConfigurationId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>ConfigurationId</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Position</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipName>Steps</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Step</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SubscribeConfiguration__c.object
<CustomObject>
    <fields>
        <fullName>EventType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Event Type</label>
        <referenceTo>EventType__c</referenceTo>
        <relationshipLabel>Subscribe Configurations</relationshipLabel>
        <relationshipName>SubscribeConfigurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscribe Configuration</label>
    <nameField>
        <label>What does this step do?</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscribe Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PublishHelpController.cls
public with sharing class PublishHelpController {
    
    public void findProblems() {
        List<Sequence__c> sequences = [
            SELECT Id, Name,
            (SELECT id, Name, Process__c, ConfigurationId__c FROM Steps__r ORDER BY Position__c ASC)
            FROM Sequence__c
            LIMIT 10000 //resolves checkmarx Queries_With_No_Where_Or_Limit_Clause
        ];
        
        Process__c publishProcess = [
            SELECT Id
            FROM Process__c
            WHERE FullyQualifiedClassName__c = :Publish.class.getName()
        ];
        
        Map<Id,SObject> publishConfigurationIdToPublishConfiguration = SalesforceObjectSet.mapAll(PublishConfiguration__c.SObjectType);
        List<SubscribeConfiguration__c> SubscribeConfigurations = SalesforceObjectSet.listAll(SubscribeConfiguration__c.SObjectType);
        Map<Id,SObject> eventTypeIdToEventType = SalesforceObjectSet.mapAll(EventType__c.SObjectType);
        
        for (Sequence__c sequence : sequences) {
            Boolean containsPublish = false;
            for (Step__c step : sequence.Steps__r) if (step.Process__c == PublishProcess.Id) containsPublish = true;
            
            //no publish steps to check
            if (!containsPublish) continue;
            
            for (Step__c step : sequence.Steps__r) {
                //skip non-publish steps
                if (step.Process__c != publishProcess.Id) continue;
                
                Id stepId = step.Id;
                Id publishConfigurationId = (Id) step.ConfigurationId__c; // cast from string to Id
                
                PublishConfiguration__c publishConfiguration;
                Id eventTypeId;
                publishConfiguration = (PublishConfiguration__c)publishConfigurationIdToPublishConfiguration.get(publishConfigurationId);
                eventTypeId = publishConfiguration.EventType__c;
                
                if (eventTypeId == null) {
                    ApexPages.addMessage(new ApexPages.Message(
                        ApexPages.Severity.WARNING,
                        'No event type has been configured on ' + publishConfigurationId
                    ));
                    continue;
                }
                
                Boolean subscriberFound = false;
                for (SubscribeConfiguration__c SubscribeConfiguration : SubscribeConfigurations) {
                    if (SubscribeConfiguration.EventType__c == eventTypeId) {
                        subscriberFound = true;
                    }
                }
                
                if (!subscriberFound) {
                    ApexPages.addMessage(new ApexPages.Message(
                        ApexPages.Severity.WARNING,
                        'There are no subscribers listening to the event on ' + publishConfigurationId
                    ));
                }
            }
        }
    }
    
}