src/objects/JumpStepConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds jump configs.</description>
    <fields>
        <fullName>Sequence__c</fullName>
        <description>Sequence name?</description>
        <inlineHelpText>What sequence should messages be copied to?</inlineHelpText>
        <label>Sequence Name</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Jump Step Config</label>
</CustomObject>

src/objects/Sequence__c.object
<CustomObject>
    <customHelpPage>SequenceHelp</customHelpPage>
    <label>Sequence</label>
    <nameField>
        <label>Sequence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Step__c.object
<CustomObject>
    <label>Step</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/JumpService.cls
public class JumpService extends ApexClassModel.Service {
    void callout(Map<String,Object> inputEvent) {}

    public class Definition extends ApexClassModel.Definition {
        String Tag = 'Services';
        String Label = 'Jump';
        String Description = 'Diverts the event to another sequence, never to return.';
        String StepConfig = JumpStepConfig__c.class.getName();
        String Icon = 'arrow_switch';
        Integer Chunks = 200; //no soqls, no dmls
        String Cardinality = 'Zero';
    }
    
    public class ServiceException extends Exception {}
    
    List<Map<String,Object>> execute(Map<String,Object> inputEvent) {
        
        Id stepConfigId = (Id)inputEvent.get('StepConfigId');
        if (stepConfigId == null) throw new ServiceException('Null step config id.');
        
        JumpStepConfig__c config;
        List<JumpStepConfig__c> jumpStepConfigs = JumpStepConfig__c.getAll().values(); //fetch without using soql
        for (JumpStepConfig__c jumpStepConfig : jumpStepConfigs) if (jumpStepConfig.Id == stepConfigId) config = jumpStepConfig;
        
        String route = (String)inputEvent.get('Route');
        if (route == null) throw new ServiceException('Null route.');
        
        Step__c step = Step__c.getValues(route);
        if (step == null) throw new ServiceException('Null step.');
        
        if (step.Sequence__c == config.Sequence__c) {
            //prevent recursion
            throw new ServiceException('Not allowed to jump to own sequence.');
        }
        
        Map<String,Object> outputEvent = new Map<String,Object>{
            'ToSequence' => config.Sequence__c
        };
        
        return new List<Map<String,Object>>{outputEvent};
    }

}