src/objects/JumpConfig__c.object
<CustomObject>
    <customHelpPage>JumpConfigHelp</customHelpPage>
    <fields>
        <fullName>Sequence__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To which sequence should messages be permanently diverted, permanently?</inlineHelpText>
        <label>Sequence</label>
        <referenceTo>Sequence__c</referenceTo>
        <relationshipLabel>Jump Configs</relationshipLabel>
        <relationshipName>JumpConfigs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Jump Config</label>
    <nameField>
        <label>What does this step do?</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jump Config</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process__c.object
<CustomObject>
    <customHelpPage>ProcessHelp</customHelpPage>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sequence__c.object
<CustomObject>
    <customHelpPage>SequenceHelp</customHelpPage>
    <label>Sequence</label>
    <nameField>
        <label>Sequence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Step__c.object
<CustomObject>
    <fields>
        <fullName>Process__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipName>Steps</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Step</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ConfigStepExtensionTest.cls
@IsTest public class ConfigStepExtensionTest {

    static testmethod void testRedirectOccurs() {
        //arrange process, sequence and step
        Process__c terminateProcess = ProcessModel.generateOne(Terminate.class);
        
        Sequence__c sequence = new Sequence__c(Name = 'Test');
        insert sequence;
        
        Step__c terminateStep = StepModel.generateOne(sequence.Id, terminateProcess.Id);
        
        JumpConfig__c config = new JumpConfig__c();
        ApexPages.StandardController controller = new ApexPages.StandardController(config);
        ConfigStepExtension extension = new ConfigStepExtension(controller);
        
        //act
        PageReference redirect = extension.doRedirect();
        
        //assert
        String id = String.valueOf(terminateStep.Id).left(15);
        System.assert(redirect.getUrl().contains(id));
    }

}