src/objects/JumpConfiguration__c.object
<CustomObject>
    <label>Jump Configuration</label>
    <nameField>
        <label>What does this step do?</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jump Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process__c.object
<CustomObject>
    <customHelpPage>ProcessHelp</customHelpPage>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sequence__c.object
<CustomObject>
    <customHelpPage>SequenceHelp</customHelpPage>
    <label>Sequence</label>
    <nameField>
        <label>Sequence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Step__c.object
<CustomObject>
    <fields>
        <fullName>Process__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipName>Steps</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Step</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ConfigurationShowStepExtensionTest.cls
@IsTest public class ConfigurationShowStepExtensionTest {

    static testMethod void testRedirectOccurs() {
        //arrange process, sequence and step
        Process__c terminateProcess = ProcessSet.generateOne(Terminate.class);
        
        Sequence__c sequence = new Sequence__c(Name = 'Test');
        insert sequence;
        
        Step__c terminateStep = StepSet.generateOne(sequence.Id, terminateProcess.Id);
        
        JumpConfiguration__c configuration = new JumpConfiguration__c();
        ApexPages.StandardController controller = new ApexPages.StandardController(configuration);
        ConfigurationShowStepExtension extension = new ConfigurationShowStepExtension(controller);
        
        //act
        PageReference redirect = extension.doRedirect();
        
        //assert
        String id = String.valueOf(terminateStep.Id).left(15);
        System.assert(redirect.getUrl().contains(id));
    }

}