src/objects/JumpConfig__c.object
<CustomObject>
    <customHelpPage>JumpConfigHelp</customHelpPage>
    <fields>
        <fullName>Sequence__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To which sequence should messages be permanently diverted, permanently?</inlineHelpText>
        <label>Sequence</label>
        <referenceTo>Sequence__c</referenceTo>
        <relationshipLabel>Jump Configs</relationshipLabel>
        <relationshipName>JumpConfigs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Jump Config</label>
    <nameField>
        <label>What does this step do?</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jump Config</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sequence__c.object
<CustomObject>
    <customHelpPage>SequenceHelp</customHelpPage>
    <label>Sequence</label>
    <nameField>
        <label>Sequence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Jump.cls
public with sharing class Jump {

    public String Parameters;
    public SObject StepConfig;

    public class Meta {
        public String Tag = 'Event Driven Architecture';
        public String Name = 'Jump';
        public String Description = 'Permanently diverts the message to another sequence, never to return.';
        public SObject StepConfig = JumpConfig__c.SObjectType.newSObject();
        public String Icon = 'arrow_switch';
        public String HelpUrl = Page.JumpConfigCsh.getUrl();
    }
    
    override public String toString() {
        Map<String,Object> parameters = (Map<String,Object>)Json.deserializeUntyped(this.Parameters);
        
        //get destination from config
        JumpConfig__c config = (JumpConfig__c)this.StepConfig;
        Sequence__c sequence = (Sequence__c)SalesforceObject.getById(config.Sequence__c);
        
        parameters.put('eda_SequenceName', sequence.Name);
        parameters.put('eda_Position', 0);
        
        return Json.serialize(new List<Map<String,Object>>{parameters});
    }

}