src/objects/LogConfiguration__c.object
<CustomObject>
    <label>Log Configuration</label>
    <nameField>
        <label>What does this step do?</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Log Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LogGroup__c.object
<CustomObject>
    <customHelpPage>LogHelp</customHelpPage>
    <fields>
        <fullName>LogConfiguration__c</fullName>
        <inlineHelpText>What record configures the Log Initializer Step that the message was passing through?</inlineHelpText>
        <label>Log Configuration</label>
        <referenceTo>LogConfiguration__c</referenceTo>
        <relationshipLabel>Log Groups</relationshipLabel>
        <relationshipName>LogGroups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Log Group</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Log Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LogConfigurationControllerTest.cls
@isTest
private class LogConfigurationControllerTest{
    private static testMethod void controllerCoverage ()  { 
        // arrange
        LogConfiguration__c  logConfiguration = new LogConfiguration__c();
        insert logConfiguration;
        ApexPages.StandardController controller = new ApexPages.StandardController(logConfiguration);
        LogConfigurationController logConfigurationController =  new LogConfigurationController(controller);
        
        // act 
        System.PageReference pageRef = logConfigurationController.LogGroupView();    
    }
    
    
    private static testMethod void callingGetLogGroupPageReferenceReturnsExpectedPageReference ()  { 
    
        // arrange
        LogConfiguration__c  logConfiguration = new LogConfiguration__c();
        insert logConfiguration;
        Id logConfigurationId = logConfiguration.Id;
        String logGroupKeyPrefix  = LogGroup__c.SObjectType.getDescribe().getKeyPrefix();  
        String fakeLookUpFieldId = '000000000000000';
          
        // act
        System.PageReference pageRef  = LogConfigurationController.getLogGroupPageReference(logConfigurationId);
        
        
        // assemble
        String actualUrl = pageRef.getUrl();

                                    
        // assert
        String expectedUrl1 =  '/' + logGroupKeyPrefix ;
        String expectedUrl2 =  'rlid=' + fakeLookUpFieldId;
        String expectedUrl3 =  'id=' + logConfigurationId;
        System.assert(actualUrl.contains(expectedUrl1) );
        System.assert(actualUrl.contains(expectedUrl2) );
        System.assert(actualUrl.contains(expectedUrl3) );
    }
}