src/objects/Message__c.object
<CustomObject>
    <customHelpPage>MessageHelp</customHelpPage>
    <fields>
        <fullName>Parameters__c</fullName>
        <inlineHelpText>What is the JSON object representing the parameters carried by this message?</inlineHelpText>
        <label>Parameters</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Message</label>
    <nameField>
        <displayFormat>N-{0000000000}</displayFormat>
        <label>Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MessageShowDataExtension.cls
public class MessageShowDataExtension {
    
    private ApexPages.StandardController controller;
    
    public MessageShowDataExtension(ApexPages.StandardController controller) {
        this.controller = controller;
    }
    
    public PageReference doRedirect() {
        Message__c message = (Message__c)SalesforceObject.getById(this.controller.getId());
        Map<String,Object> parameters = (Map<String,Object>)Json.deserializeUntyped(message.Parameters__c);
        
        try {
            Id dataId = (Id)parameters.get('id');
            SObject dataObject = SalesforceObject.getById(dataId);
            return new ApexPages.StandardController(dataObject).view();
        } catch (Exception e) {
            return new ApexPages.StandardController(this.controller.getRecord()).view();
        }
    }

}