src/objects/Message__c.object
<CustomObject>
    <customHelpPage>MessageHelp</customHelpPage>
    <fields>
        <fullName>Exception__c</fullName>
        <inlineHelpText>If the process threw an exception when handling this message, what was the error text?</inlineHelpText>
        <label>Exception</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>What stage of its lifecycle is this message at?</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Buffer</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reprocess</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Message</label>
    <nameField>
        <displayFormat>N-{0000000000}</displayFormat>
        <label>Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MessageListExtension.cls
public with sharing class MessageListExtension {
    
    public ApexPages.StandardSetController SetController;
    public ApexPages.StandardSetController MessageSetController {public get; private set;}
    
    public MessageListExtension(ApexPages.StandardSetController setController) {
        this.SetController = setController;
    
        //set up message standard set controller
        this.MessageSetController = new ApexPages.StandardSetController(buildQueryLocator());
        this.MessageSetController.setPageSize(100);
    }
    
    public void doInit() {
        try {
            Type.forName(DoDml.class.getName()).newInstance();
        } catch (Exception e) {
            e.setMessage('MessageListExtension.doInit: ' + e.getMessage());
            ApexPages.addMessages(e);
        }
    }
    
    public PageReference doPause() {
        MessageSetModel.pauseQueue();
        PageReference messageList = Page.MessageList;
        messageList.setRedirect(true);
        return messageList;
    }
    
    public PageReference doResume() {
        MessageSetModel.resumeQueue();
        PageReference messageList = Page.MessageList;
        messageList.setRedirect(true);
        return messageList;
    }
    
    static private Database.QueryLocator buildQueryLocator() {
        String query = ''
            + ' SELECT Id, Name, CreatedDate, Status__c, Route__c, ExecuteDuration__c, Exception__c'
            + ' FROM Message__c'
            + ' WHERE Status__c = \'Completed\''
            + ' AND Exception__c = null'
            + ' ORDER BY CreatedDate DESC'
            + ' LIMIT 10000'
            + ' ALL ROWS'
        ;
        
        return Database.getQueryLocator(query);
    }
    
    public class DoDml {
        public DoDml() {
            //avoids dml in action method
            MessageSetModel.locateFailedOneShots().healExtendedStatus();
        }
    }
}