src/objects/Message__c.object
<CustomObject>
    <customHelpPage>MessageHelp</customHelpPage>
    <fields>
        <fullName>Exception__c</fullName>
        <inlineHelpText>If the process threw an exception when handling this message, what was the error text?</inlineHelpText>
        <label>Exception</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Parameters__c</fullName>
        <inlineHelpText>What is the JSON object representing the parameters carried by this message?</inlineHelpText>
        <label>Parameters</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>What stage of its lifecycle is this message at?</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Buffer</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reprocess</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Message</label>
    <nameField>
        <displayFormat>N-{0000000000}</displayFormat>
        <label>Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MessageProcessExtension.cls
public with sharing class MessageProcessExtension {
    
    static private Message__c message;
    
    public MessageProcessExtension(ApexPages.StandardController controller) {
        message = [
            SELECT Id, Status__c, Parameters__c
            FROM Message__c
            WHERE Id = :controller.getId()
        ];
    }
    
    public PageReference doProcess() {
        //we are happy for Queued, Buffered or Processing guys to be force-Processed
        //but we just note that a Queued message will need to be resolved first!
        if (message.Status__c == 'Queued') {
            //message was paused, resolve here
            Broker.resolve(new List<Message__c>{message}); //RESOLVE
        }
        
        //write away status and any resolved fields ("avoids DML in action method")
        Type.forName(DoDml.class.getName()).newInstance(); //PERSIST
        
        //restart the broker
        Broker.process();
        
        //redirect back to list view
        return new ApexPages.PageReference('/' + SObjectType.Message__c.KeyPrefix);
    }

    public class DoDml {
        public DoDml() {
            message.Exception__c = null;
            message.Status__c = 'Reprocess';
            update message;
        }
    }
    
}