src/objects/Message__c.object
<CustomObject>
    <customHelpPage>MessageHelp</customHelpPage>
    <fields>
        <fullName>Parameters__c</fullName>
        <inlineHelpText>What is the JSON object representing the parameters carried by this message?</inlineHelpText>
        <label>Parameters</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Message</label>
    <nameField>
        <displayFormat>N-{0000000000}</displayFormat>
        <label>Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MessageShowDataExtensionTest.cls
@IsTest public class MessageShowDataExtensionTest {

    static testmethod void testRedirect() {
        //arrange
        String parameters = Json.serialize(new Map<String,Object>{'Id' => UserInfo.getUserId()});
        Message__c message = new Message__c(Parameters__c = parameters);
        insert message;
        
        ApexPages.StandardController controller = new ApexPages.StandardController(message);
        MessageShowDataExtension extension = new MessageShowDataExtension(controller);
        
        //act
        PageReference redirect = extension.doRedirect();
        
        //assert
        String expectedUrl = String.valueOf(UserInfo.getUserId()).left(15);
        String actualUrl = redirect.getUrl();
        System.assert(actualUrl.contains(expectedUrl));
    
    }

}