src/objects/Message__c.object
<CustomObject>
    <customHelpPage>MessageHelp</customHelpPage>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>What stage of its lifecycle is this message at?</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Buffer</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reprocess</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Message</label>
    <nameField>
        <displayFormat>N-{0000000000}</displayFormat>
        <label>Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MessageReprocessExtension.cls
public class MessageReprocessExtension {
    
    static Id messageId;
    
    private ApexPages.StandardController controller;
    
    public MessageReprocessExtension(ApexPages.StandardController controller) {
        MessageReprocessExtension.messageId = controller.getId();
        this.controller = controller;
    }
    
    public PageReference doReprocess() {
        Type.forName(DoDml.class.getName()).newInstance();
        Broker.process();
        
        String prefix = SObjectType.Message__c.KeyPrefix;
        return new ApexPages.PageReference('/' + prefix + '/o');
    }

    public class DoDml {
        public DoDml() {
            Database.update(new Message__c(
                Id = messageId,
                Message__c = null,
                Status__c = 'Reprocess'
            ));
        }
    }
    
}