src/objects/Message__c.object
<CustomObject>
    <customHelpPage>MessageHelp</customHelpPage>
    <fields>
        <fullName>Sequence__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Which Sequence is this message progressing through?</inlineHelpText>
        <label>Sequence</label>
        <referenceTo>Sequence__c</referenceTo>
        <relationshipLabel>Messages</relationshipLabel>
        <relationshipName>Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Message</label>
    <nameField>
        <displayFormat>N-{0000000000}</displayFormat>
        <label>Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sequence__c.object
<CustomObject>
    <customHelpPage>SequenceHelp</customHelpPage>
    <label>Sequence</label>
    <nameField>
        <label>Sequence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SubsequenceStepConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds subsequence configs.</description>
    <fields>
        <fullName>Sequence__c</fullName>
        <description>Sequence name?</description>
        <inlineHelpText>Through which sequence should messages be diverted, before they progress to the next step?</inlineHelpText>
        <label>Sequence name</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Subsequence Step Config</label>
</CustomObject>

src/classes/SubsequenceService.cls
public class SubsequenceService extends ApexClassModel.Service {
    void callout(Map<String,Object> inputEvent) {}
    
    static public Boolean IsRunning = false;
    
    public class Summary extends ApexClassModel.Summary {
        String Tag = 'Service Bus';
        String Label = 'Subsequence';
        String Description = 'Synchronously executes another sequence before emitting the event.';
        String StepConfig = SubsequenceStepConfig__c.class.getName();
        String Icon = 'arrow_undo';
        Integer Chunks = 1; //we dont know what they will do
        String Cardinality = 'One';
    }
    
    public class ServiceException extends Exception {}
    
    public void traverse(Map<String,Object> inputEvent) {
        
        //#1147 no Message__c or persist() here! manually route any outputs to next step
        String route = (String)inputEvent.get('Route');
        String sequence = route.substringAfter('#').substringBefore('#');
        Integer version = Integer.valueOf(route.substringBefore('#'));
        Integer position = Integer.valueOf(route.substringAfterLast('#'));
        inputEvent.put('Route', version + '#' + sequence + '#' + (position + 1));
        ApexClassModel model = ApexClassModel.fromRoute((String)inputEvent.get('Route'));
        
        //invoke callouts (this WILL explode, by design)
        model.invokeCallout(inputEvent);
        
        //invoke execute
        List<Map<String,Object>> outputEvents = model.invokeExecute(inputEvent);
        
        for (Map<String,Object> outputEvent : outputEvents) {
            //recurse into each output
            this.traverse(outputEvent);
        }
    }
    
    List<Map<String,Object>> execute(Map<String,Object> inputEvent) {
        
        //#995 help subsequence bail out
        IsRunning = true;
        
        String stepConfigId = (Id)inputEvent.get('StepConfigId');
        if (stepConfigId == null) throw new ServiceException('Null step config id.');
        
        SubsequenceStepConfig__c config = [
            SELECT Id, Sequence__c
            FROM SubsequenceStepConfig__c
            WHERE Id = :stepConfigId
        ];
        
        //sorry, no callouts in subsequences
        Savepoint savepoint = Database.setSavepoint();
        
        try {
            //#1147 no persist happening here, gotta do our own routing!
            String route = (String)inputEvent.get('Route');
            Integer version = Integer.valueOf(route.substringBefore('#'));
            Integer position = 0;
            
            //he has inputs but no outputs
            Map<String,Object> clone = inputEvent.clone();
            clone.put('Route', version + '#' + config.Sequence__c + '#' + position);
            this.traverse(clone);
            
        } catch (MessageModel.ModelException e) {
            //TODO catch "callouts not supported in subsequence, jump out and jump back"
            Database.rollback(savepoint);
            throw e;
        }
        
        return new List<Map<String,Object>>{inputEvent};
    }
}