src/objects/Message__c.object
<CustomObject>
    <customHelpPage>MessageHelp</customHelpPage>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>What stage of its lifecycle is this message at?</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Buffer</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reprocess</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Message</label>
    <nameField>
        <displayFormat>N-{0000000000}</displayFormat>
        <label>Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MessageRebufferExtension.cls
public with sharing class MessageRebufferExtension {
    
    private ApexPages.StandardSetController controller;
    @TestVisible static private List<Message__c> messages;
    
    public MessageRebufferExtension(ApexPages.StandardSetController controller) {
        this.controller = controller;
    }
    
    public PageReference doRebuffer() {
        Set<Id> messageIds = new Map<Id,SObject>(this.controller.getSelected()).keySet();
        messages = [SELECT Id, Status__c FROM Message__c WHERE Id IN :messageIds AND Status__c = 'Started'];
        for (Message__c message : messages) message.Status__c = 'Rebuffered';
        
        //write status and any exception fields ("avoids DML in action method")
        Type.forName(DoDml.class.getName()).newInstance();
        return new ApexPages.PageReference('/' + SObjectType.Message__c.KeyPrefix);
    }
    
    public class DoDml {
        public DoDml() {
            update messages;
            //restart REAL broker
            Broker.run();
        }
    }
    
}