src/objects/Message__c.object
<CustomObject>
    <customHelpPage>MessageHelp</customHelpPage>
    <fields>
        <fullName>Exception__c</fullName>
        <inlineHelpText>If the process threw an exception when handling this message, what was the error text?</inlineHelpText>
        <label>Exception</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>What stage of its lifecycle is this message at?</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Buffer</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reprocess</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Which Step is this message destined for?</inlineHelpText>
        <label>Step</label>
        <referenceTo>Step__c</referenceTo>
        <relationshipLabel>Messages</relationshipLabel>
        <relationshipName>Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Message</label>
    <nameField>
        <displayFormat>N-{0000000000}</displayFormat>
        <label>Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/NamespaceSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Holds the namespace prefix needed to normalize custom buttons URLs and javascript.</description>
    <fields>
        <fullName>Prefix__c</fullName>
        <description>Raw namespace prefix, eg &apos;esb&apos; or null</description>
        <inlineHelpText>What is my namespace prefix?</inlineHelpText>
        <label>Prefix</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Setting</label>
</CustomObject>

src/objects/Step__c.object
<CustomObject>
    <label>Step</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MonitorController.cls
public with sharing class MonitorController {
    
    public void doPing() {}
    
    public Boolean getIsBrokerRunning() {
        return Job.isScheduled() || Job.isRunning();
    }
    
    public Boolean getIsJobsWaiting() {
        //find existing jobs
        Integer existingQueueableJobs = [
            SELECT COUNT()
            FROM AsyncApexJob
            WHERE ApexClass.NamespacePrefix = :NamespaceSetting__c.getOrgDefaults().Prefix__c
            AND ApexClass.Name = 'Job'
            AND JobType = 'Queueable'
            AND Status IN ('Queued', 'Processing', 'Preparing')
        ];
        
        return existingQueueableJobs != 0;
    }
    
    public class Statistic {
        public Statistic(String apexClassName, Integer paused, Integer buffered, Integer started, Integer exceptions) {
            this.ApexClassName = apexClassName;
            this.Paused = paused;
            this.Buffered = buffered;
            this.Started = started;
            this.Exceptions = exceptions;
        }
        
        public String ApexClassName {get; set;}
        public Integer Paused {get; set;}
        public Integer Buffered {get; set;}
        public Integer Started {get; set;}
        public Integer Exceptions {get; set;}
    }
    
    @RemoteAction static public List<Statistic> getTestStatistics() {
        return new List<Statistic>{
            new Statistic(null,               1, 32,  0,  0),
            new Statistic('Branch',          1,  0,  0,  0),
            new Statistic('GateByEntryPoint',         2,  0,  0,  0),
            new Statistic('GateByJob',         2,  0,  0,  0),
            new Statistic('Jump',         2,  0,  0,  0),
            new Statistic('Publish',         1,  0,  4,  0),
            new Statistic('Schedule',            2,  0,  0,  0),
            new Statistic('Subscribe',1,  0,  0,  0),
            new Statistic('Subsequence',     2,  0,  2,  0),
            new Statistic('Terminate',       2,  0,  9,  0),
            new Statistic('Wiretap',       2,  0,  9,  0)
        };
    }
    
    @RemoteAction static public List<Statistic> getStatistics() {
        Map<String,Statistic> route2statistic = new Map<String,Statistic>();
        
        //initialize empty statistics for each route
        for (AggregateResult result : [
            SELECT Step__c route
            FROM Message__c
            GROUP BY Step__c
        ]) {
            Statistic statistic = new Statistic((String)result.get('route'), 0, 0, 0, 0);
            route2statistic.put((String)result.get('route'), statistic);
        }
        
        //#761 add null guy for unrouted messages
        route2statistic.put(null, new Statistic(' ', 0, 0, 0, 0));
        
        //check for null so we don't blow up for unresolved messages
        for (AggregateResult result : [
            SELECT Step__c route, COUNT(Status__c) total
            FROM Message__c
            WHERE Status__c = 'Paused'
            GROUP BY Step__c
        ]) {
            Statistic statistic = route2statistic.get((String)result.get('route')); //#761
            if (statistic == null) statistic = route2statistic.get(null);
            statistic.Paused += (Integer)result.get('total');
        }
        
        for (AggregateResult result : [
            SELECT Step__c route, COUNT(Status__c) total
            FROM Message__c
            WHERE Status__c = 'Buffered'
            GROUP BY Step__c
        ]) {
            Statistic statistic = route2statistic.get((String)result.get('route')); //#761
            if (statistic == null) statistic = route2statistic.get(null);
            statistic.Buffered += (Integer)result.get('total');
        }
        
        for (AggregateResult result : [
            SELECT Step__c route, COUNT(Status__c) total
            FROM Message__c
            WHERE Status__c = 'Started' AND Exception__c = null
            GROUP BY Step__c
        ]) {
            Statistic statistic = route2statistic.get((String)result.get('route')); //#761
            if (statistic == null) statistic = route2statistic.get(null);
            statistic.Started += (Integer)result.get('total');
        }
        
        for (AggregateResult result : [
            SELECT Step__c route, COUNT(Status__c) total
            FROM Message__c
            WHERE Status__c = 'Started' AND Exception__c != null
            GROUP BY Step__c
        ]) {
            Statistic statistic = route2statistic.get((String)result.get('route')); //#761
            if (statistic == null) statistic = route2statistic.get(null);
            statistic.Exceptions += (Integer)result.get('total');
        }
        
        //pluck out the buffered guys (null per #697)
        Statistic none = route2statistic.remove(null);
        List<String> stepNames = new List<String>(route2statistic.keySet());
        stepNames.sort();
        
        //sort buffered then alphabetical
        List<Statistic> statistics = new List<Statistic>{none};
        for (String stepName : stepNames) statistics.add(route2statistic.get(stepName));
        return statistics;
    }
    
}