src/objects/NamespaceSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Holds the namespace prefix needed to normalize custom buttons URLs and javascript.</description>
    <fields>
        <fullName>Prefix__c</fullName>
        <description>Raw namespace prefix, eg &apos;esb&apos; or null</description>
        <inlineHelpText>What is my namespace prefix?</inlineHelpText>
        <label>Prefix</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Setting</label>
</CustomObject>

src/classes/ApexClassSummaryExtensionTest.cls
@IsTest class ApexClassSummaryExtensionTest {

    @TestSetup static void testSetup() {
        new PostInstallHandler().upsertNamespaceSetting();
    }
    
    static testmethod void coverCode() {
        //arrange controller and extension
        ApexClass apexClass = [SELECT Id FROM ApexClass WHERE Name = 'Terminate' AND NamespacePrefix = :NamespaceSetting__c.getOrgDefaults().Prefix__c];
        ApexPages.StandardController controller = new ApexPages.StandardController(apexClass);
        ApexClassSummaryExtension extension = new ApexClassSummaryExtension(controller);
        
        //act
        extension.doInit();
        
        //assert
        System.assert(!ApexPages.hasMessages(), 'Wrong messages.');
    }
    
}