src/objects/OAuthSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Holds the credentials needed to manage the Broker running user context. #774 formerly OAuth Setting</description>
    <fields>
        <fullName>AccessToken__c</fullName>
        <description>Roaring and ready access token that can be used to invoke Salesforce APIs.</description>
        <label>Access Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Setting</label>
</CustomObject>

src/objects/Process__c.object
<CustomObject>
    <customHelpPage>ProcessHelp</customHelpPage>
    <fields>
        <fullName>FullyQualifiedClassName__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>What is the underlying namespace prefix and Apex class name used by this process?</inlineHelpText>
        <label>Fully Qualified Class Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ConfigureController.cls
public with sharing class ConfigureController {
    
    /**
     * Sometimes the CronJobDetail takes a while to populate.
     * We are happy enough knowing just the CronJob Id exists
     * in order to display that the Scheduled Job is alright.
     * This gives immediate feedback when you press
     * "Click here to schedule the job to fix this"
     */
    private Id CronDetailId;
    
    private AppMenuItem AppMenuItem;
    private AppMenuItem getAppMenuItem() {
        if (this.AppMenuItem == null) this.AppMenuItem = [SELECT Id, StartUrl FROM AppMenuItem WHERE Name = 'EnterpriseServiceBus'];
        return this.AppMenuItem;
    }
    
    private List<CronJobDetail> CronJobDetails;
    private List<CronJobDetail> getCronJobDetails() {
        if (this.CronJobDetails == null) this.CronJobDetails = [SELECT Id FROM CronJobDetail WHERE Name = 'Heartbeat (do not delete)'];
        return this.CronJobDetails;
    }
    
    private List<Process__c> Processes;
    private List<Process__c> getProcesses() {
        if (this.Processes == null) this.Processes = [SELECT Id FROM Process__c WHERE FullyQualifiedClassName__c = :Terminate.class.getName()];
        return this.Processes;
    }
    
    private String HomeContent;
    private String getHomeContent() {
        if (this.HomeContent == null) this.HomeContent = Test.isRunningTest() ? '' : new PageReference('/home/home.jsp').getContent().toString();
        return this.HomeContent;
    }
    
    /**
     * eg "https://pod.salesforce.com"
     */
    public String getPodProtocolAndHost() {
        return RemoteSiteSettingController.protocolAndHost;
    }
    
    /**
     * If we don't have an OAuthSetting__c with an AccessToken__c this
     * quickly sends us through the dance to get that set up correctly.
     */
    public PageReference initOAuth() {
        PageReference retURL = ApexPages.currentPage();
        return OAuthController.doDanceIfNeeded(retURL);
    }
    
    /**
     * The Heartbeat scheduled job is required for the 'Schedule' process to run.
     * If a System Administrator inadvertently deletes it, it can be recreated here.
     */
    public Boolean getHasHeartbeat() {
        if (this.CronDetailId != null) return true;
        return this.getCronJobDetails().size() == 1;
    }
    
    public void doSetupHeartbeat() {
        //schedule the job
        this.CronDetailId = PostInstallHandler.installSchedule();
    }
    
     /**
     * Detect if Remote Site Setting is deployed
     */
    public Boolean HasRemoteSiteSetting {get; set;}
    public void detectRemoteSiteSetting() {
        this.HasRemoteSiteSetting = RemoteSiteSettingController.isRssPresent;
    }
    
    /**
     * Is EVERYTHING installed correctly?
     */
    public Boolean getIsOk() {
        return this.getHasHeartbeat();
    }
    
    public PageReference doGetStarted() {
        return new PageReference(this.getAppMenuItem().StartUrl);
    }
    
}