src/objects/Process__c.object
<CustomObject>
    <customHelpPage>ProcessHelp</customHelpPage>
    <fields>
        <fullName>ConfigObject__c</fullName>
        <inlineHelpText>Optionally, what is the API name of a Custom Object used to configure instances of this process?</inlineHelpText>
        <label>Config Object</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomSetting__c</fullName>
        <inlineHelpText>Optionally, what is the API name of a Custom Setting used to hold any global options for this process?</inlineHelpText>
        <label>Custom Setting</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>What does this process do?</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>DocsPageUrl__c</fullName>
        <inlineHelpText>Where is the supporting documentation provided by the author of this process?</inlineHelpText>
        <label>Docs Page URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>FullyQualifiedClassName__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>What is the underlying namespace prefix and Apex class name used by this process?</inlineHelpText>
        <label>Fully Qualified Class Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Icon__c</fullName>
        <inlineHelpText>What is the name of the icon that represents this process? (From http://www.famfamfam.com/lab/icons/silk/previews/index_abc.png)</inlineHelpText>
        <label>Icon</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tag__c</fullName>
        <inlineHelpText>What is the tag name? Processes grouped with the same tag name will appear together.</inlineHelpText>
        <label>Tag</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProcessObject.cls
public with sharing class ProcessObject extends SalesforceObject {
    
    public without sharing class ProcessException extends Exception {}
    
    public ProcessObject(Process__c process) {
        super(process);
    }
    
    /**
     * This class is a template that must exist in every Process. It describes extra metadata around a process that
     * isn't appropriate for Tag, Description, InputParameters or OutputParameters. This inner class must be present
     * for an apex class to appear in the Process list.
     */
    @TestVisible private without sharing class Meta {
        /**
         * Each process MUST provide a grouping tag.
         */
        public String Tag;

        /**
         * Each process MUST provide a friendly name.
         */
        public String Name;

        /**
         * Each process MUST provide a succinct description.
         */
        public String Description;

        /**
         * Each Process can have one associated customization in the form of a Custom Setting. Process Authors must
         * advertise the custom setting type here, and the framework will provide a link from the Process detail page.
         */
        public SObject CustomSetting;
        
        /**
         * Each Step can have one associated configuration record. The type of the record depends on what process
         * is living on the Step. Process Authors must advertise the object type here, and the framework will
         * handle the record lifecycle (creating and deleting them in tandem with the appropriate Step).
         */
        public SObject ConfigObject;
        
        /**
         * Each Process must name an icon (eg 'arrow_left') from the FamFamFam Silk library:
         * http://www.famfamfam.com/archive/silk-icons-thats-your-lot/
         */
        public String Icon;
        
        /**
         * Each Process can have one Visualforce Page for support and documentation purposes. Process Authors can
         * populate the property with a default value like Page.MyProcessDocs.getUrl() to make this available to users.
         */
        public String DocsPageUrl;
        
        //Inputs
        //Outputs
    }
    
    /**
     * Generates an inserted Process from a Type
     *
     * @param reflector Type of class whose process to generate
     * @return          Inserted process with all fields
     */
    @TestVisible static private Process__c generateOne(Type reflector) {
        if (!SObjectType.Process__c.Createable) throw new Broker.CrudException('!SObjectType.Process__c.Createable');
            
        Process__c process = fromType(reflector);
        insert process;
        return process;
    }
    
    public without sharing class Context {
        public Process__c contextFromType(Type reflector) {
            Type outerClass = reflector;
            Type innerClass = Type.forName(reflector.getName() + '.' + 'Meta');
            
            Object impl = outerClass.newInstance();
            Process__c process = new Process__c(
                FullyQualifiedClassName__c = outerClass.getName()
            );
            
            //special exception for BrokerTest.FailureProcess as used in testing
            if (reflector.getName() == BrokerTest.class.getName()) return process;
            
            ProcessObject.Meta meta = (ProcessObject.Meta)Json.deserialize(Json.serialize(innerClass.newInstance()), ProcessObject.Meta.class);

            if (meta.Tag == null) {
                //EVERY PROCESS MUST PROVIDE A TAG
                throw new ProcessException('Process "' + process.FullyQualifiedClassName__c + '" must provide Meta.Tag');
            }

            //attempt to populate the tag of the process
            process.Tag__c = meta.Tag;


            if (meta.Name == null) {
                //EVERY PROCESS MUST PROVIDE A NAME
                throw new ProcessException('Process "' + process.FullyQualifiedClassName__c + '" must provide Meta.Name');
            }

            //attempt to populate the tag of the process
            process.Name = meta.Name;


            if (meta.Description == null) {
                //EVERY PROCESS MUST PROVIDE A DESCRIPTION
                throw new ProcessException('Process "' + process.FullyQualifiedClassName__c + '" must provide Meta.Description');
            }

            //attempt to populate the tag of the process
            process.Description__c = meta.Description;

            if (meta.CustomSetting != null) {
                //attempt to populate the name of the customization object
                process.CustomSetting__c = meta.CustomSetting.getSObjectType().getDescribe().getName();
            }
            
            if (meta.ConfigObject != null) {
                //attempt to populate the name of the configuration object
                process.ConfigObject__c = meta.ConfigObject.getSObjectType().getDescribe().getName();
            }
            
            if (meta.Icon != null) {
                //attempt to populate the css class name of the process icon
                process.Icon__c = meta.Icon;
            } else {
               process.Icon__c = 'cog'; 
            }
            
            if (meta.DocsPageUrl != null) {
                //populate the help page url
                process.DocsPageUrl__c = meta.DocsPageUrl;
            } else {
                //EVERY PROCESS MUST PROVIDE A HELP PAGE
                throw new ProcessException('Process "' + process.FullyQualifiedClassName__c + '" must provide Meta.DocsPageUrl');
            }
            
            return process;
        }
    }
    
    /**
     * Generates an in-memory Process from a Type
     *
     * @param reflector Type of class whose process to generate
     * @return          In-memory process with all fields
     */
    static public Process__c fromType(Type reflector) {
        return new Context().contextFromType(reflector);
    }
    
}