src/objects/Process__c.object
<CustomObject>
    <customHelpPage>ProcessHelp</customHelpPage>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>What does this process do?</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>FullyQualifiedClassName__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>What is the underlying namespace prefix and Apex class name used by this process?</inlineHelpText>
        <label>Fully Qualified Class Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Icon__c</fullName>
        <inlineHelpText>What is the name of the icon that represents this process? (From http://www.famfamfam.com/lab/icons/silk/previews/index_abc.png)</inlineHelpText>
        <label>Icon</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tag__c</fullName>
        <inlineHelpText>What is the tag name? Processes grouped with the same tag name will appear together.</inlineHelpText>
        <label>Tag</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProcessDescribeController.cls
public with sharing class ProcessDescribeController {
    
    public Process__c process {public get; private set;}
    public ProcessModel.ESB ESB {public get; private set;}
    
    public ProcessDescribeController() {
        String fqn = ApexPages.currentPage().getParameters().get('fqn');
        
        this.Process = [
            SELECT Id, Name, Tag__c, Icon__c, Description__c, FullyQualifiedClassName__c
            FROM Process__c
            WHERE FullyQualifiedClassName__c = :fqn
        ];
        
        Type innerClass = Type.forName(fqn + '.' + 'ESB');
        if (innerClass == null) innerClass = Type.forName(fqn + 'ESB'); //#828
        this.ESB = (ProcessModel.ESB)Json.deserialize(Json.serialize(innerClass.newInstance()), ProcessModel.ESB.class);
    }
    
}