src/objects/Process__c.object
<CustomObject>
    <customHelpPage>ProcessHelp</customHelpPage>
    <fields>
        <fullName>FullyQualifiedClassName__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>What is the underlying namespace prefix and Apex class name used by this process?</inlineHelpText>
        <label>Fully Qualified Class Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProcessRefreshExtension.cls
public with sharing class ProcessRefreshExtension {
    
    private ApexPages.StandardController controller;
    @TestVisible static private Process__c process;
    
    public ProcessRefreshExtension(ApexPages.StandardController controller) {
        this.controller = controller;
    }
    
    public PageReference doRefresh() {
        try {
            process = (Process__c)ApexDomain.getById(this.controller.getId());
            Type reflector = Type.forName(process.FullyQualifiedClassName__c);
            
            process = ProcessModel.fromType(reflector);
            Type.forName(DoDml.class.getName()).newInstance();
        } catch (Exception e) {
            ApexPages.addMessages(e);
            return null;
        }
        
        //back to detail page
        return this.controller.view();
    }
    
    public class DoDml {
        public DoDml() {
            upsert process FullyQualifiedClassName__c;
        }
    }

}