src/objects/ScheduleConfig__c.object
<CustomObject>
    <customHelpPage>ScheduleConfigCsh</customHelpPage>
    <fields>
        <fullName>Frequency__c</fullName>
        <inlineHelpText>Does this schedule run daily, weekly or monthly?</inlineHelpText>
        <label>Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Daily</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FriendlyDates__c</fullName>
        <inlineHelpText>What pattern of days does the schedule run?</inlineHelpText>
        <label>Run Dates</label>
        <picklist>
            <controllingField>Frequency__c</controllingField>
            <picklistValues>
                <fullName>Working days only</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Weekends and holidays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>FriendlyTimes__c</fullName>
        <description>The pattern of schedule run times in GMT that the schedule runs</description>
        <inlineHelpText>What pattern of times does the schedule run? All times should be entered in GMT.</inlineHelpText>
        <label>Run Times (GMT)</label>
        <picklist>
            <picklistValues>
                <fullName>00:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>01:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09:00</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>10:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23:00</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Schedule Config</label>
    <nameField>
        <label>What does this step do?</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ScheduleConfigObjectSet.cls
public class ScheduleConfigObjectSet extends SalesforceObjectSet {
    
    public ScheduleConfigObjectSet(List<ScheduleConfig__c> sobjects) {
        super(sobjects);
    }
    
    private void populateFriendlyNames() {
        List<ScheduleConfig__c> scheduleConfigs = (List<ScheduleConfig__c>)this.getSObjects();
        Set<String> everyHour = new Set<String>{'00:00','01:00','02:00','03:00','04:00','05:00','06:00','07:00','08:00','09:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00','17:00','18:00','19:00','20:00','21:00','22:00','23:00'};
        Set<String> allDaily = new Set<String>{'Working days only','Weekends and holidays'};
        Set<String> allWeekly = new Set<String>{'Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'};
        Set<String> allMonthly = new Set<String>{'01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30'};
     
        for (ScheduleConfig__c scheduleConfig : scheduleConfigs) {
            List<String> friendlyTimes = new List<String>();
            List<String> friendlyDates = new List<String>();
            if (null != scheduleConfig.FriendlyTimes__c) friendlyTimes = scheduleConfig.FriendlyTimes__c.split(';');
            if (null != scheduleConfig.FriendlyDates__c) friendlyDates = scheduleConfig.FriendlyDates__c.split(';');
            
            String name = 'Fires this sequence ';
            
            //hourly
            if (new Set<String>(friendlyTimes).containsAll(everyHour)) {
                name += 'every hour ';
            } else {
                name += 'at ';
                name += String.join(friendlyTimes, ', ');
                name += ' ';
            }
            
            //daily
            if ('Daily' == scheduleConfig.Frequency__c) {
                if (new Set<String>(friendlyDates).containsAll(allDaily)) {
                    name += 'every day.';
                } else {
                    name += 'on ';
                    name += String.join(friendlyDates, ', ').toLowerCase();
                    name += '.';
                }
            }
            
            //weekly
            if ('Weekly' == scheduleConfig.Frequency__c) {
                if (new Set<String>(friendlyDates).containsAll(allWeekly)) {
                    name += 'every day of the week.';
                } else {
                    name += 'on ';
                    //if (friendlyDates.size() > 1) friendlyDates[friendlyDates.size() - 1] = 'and ' + friendlyDates[friendlyDates.size() - 1];
                    name += String.join(friendlyDates, 's and ');
                    name += 's.';
                }
            }
            
            //monthly
            if ('Monthly' == scheduleConfig.Frequency__c) {
                if (new Set<String>(friendlyDates).containsAll(allMonthly)) {
                    name += 'every day of the month.';
                } else {
                    name += 'on day ';
                    name += String.join(friendlyDates, ', ');
                    name += ' ';
                    name += 'of every month.';
                }
            }
            scheduleConfig.Name = name.left(80);
        }
    }
    
    override public void onBeforeUpdate(List<SObject> sobjects) {
        this.populateFriendlyNames();
    }
    
    override public void onBeforeInsert() {
        this.populateFriendlyNames();
    }

}