src/objects/ScheduleConfig__c.object
<CustomObject>
    <customHelpPage>ScheduleConfigCsh</customHelpPage>
    <fields>
        <fullName>Frequency__c</fullName>
        <inlineHelpText>Does this schedule run daily, weekly or monthly?</inlineHelpText>
        <label>Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Daily</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FriendlyDates__c</fullName>
        <inlineHelpText>What pattern of days does the schedule run?</inlineHelpText>
        <label>Run Dates</label>
        <picklist>
            <controllingField>Frequency__c</controllingField>
            <picklistValues>
                <fullName>Working days only</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Weekends and holidays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>FriendlyTimes__c</fullName>
        <description>The pattern of schedule run times in GMT that the schedule runs</description>
        <inlineHelpText>What pattern of times does the schedule run? All times should be entered in GMT.</inlineHelpText>
        <label>Run Times (GMT)</label>
        <picklist>
            <picklistValues>
                <fullName>00:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>01:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09:00</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>10:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23:00</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Should this schedule actually run or not?</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Schedule Config</label>
    <nameField>
        <label>What does this step do?</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ScheduleConfigSetModelTest.cls
@IsTest public class ScheduleConfigSetModelTest {
    
    static testmethod void testDailyFriendlyNames() {
        //act every hour of every day
        insert new ScheduleConfig__c(
            IsActive__c = true,
            Frequency__c = 'Daily',
            FriendlyTimes__c = '00:00;01:00;02:00;03:00;04:00;05:00;06:00;07:00;08:00;09:00;10:00;11:00;12:00;13:00;14:00;15:00;16:00;17:00;18:00;19:00;20:00;21:00;22:00;23:00',
            FriendlyDates__c = 'Working days only;Weekends and holidays'
        );
        
        //assemble
        ScheduleConfig__c config = [SELECT Name FROM ScheduleConfig__c];
        
        //assert
        String expectedName = 'Fires this sequence every hour every day.';
        String actualName = config.Name;
        System.assertEquals(expectedName, actualName);
    }
    
    static testmethod void testWeeklyFriendlyNames() {
        //act twice a day
        insert new ScheduleConfig__c(
            IsActive__c = true,
            Frequency__c = 'Weekly',
            FriendlyTimes__c = '09:00;17:00',
            FriendlyDates__c = 'Monday;Friday'
        );
        
        //assemble
        ScheduleConfig__c config = [SELECT Name FROM ScheduleConfig__c];
        
        //assert
        String expectedName = 'Fires this sequence at 09:00, 17:00 on Mondays and Fridays.';
        String actualName = config.Name;
        System.assertEquals(expectedName, actualName);
    }
    
    static testmethod void testMonthlyFriendlyNames() {
        //act twice a month
        insert new ScheduleConfig__c(
            IsActive__c = true,
            Frequency__c = 'Monthly',
            FriendlyTimes__c = '12:00',
            FriendlyDates__c = '07;14'
        );
        
        //assemble
        ScheduleConfig__c config = [SELECT Name FROM ScheduleConfig__c];
        
        //assert
        String expectedName = 'Fires this sequence at 12:00 on day 14, 07 of every month.';
        String actualName = config.Name;
        System.assertEquals(expectedName, actualName);
    }
    
}