src/objects/ScheduleConfig__c.object
<CustomObject>
    <customHelpPage>ScheduleConfigCsh</customHelpPage>
    <fields>
        <fullName>Frequency__c</fullName>
        <inlineHelpText>Does this schedule run daily, weekly or monthly?</inlineHelpText>
        <label>Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Daily</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FriendlyDates__c</fullName>
        <inlineHelpText>What pattern of days does the schedule run?</inlineHelpText>
        <label>Run Dates</label>
        <picklist>
            <controllingField>Frequency__c</controllingField>
            <picklistValues>
                <fullName>Working days only</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Weekends and holidays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>FriendlyTimes__c</fullName>
        <description>The pattern of schedule run times in GMT that the schedule runs</description>
        <inlineHelpText>What pattern of times does the schedule run? All times should be entered in GMT.</inlineHelpText>
        <label>Run Times (GMT)</label>
        <picklist>
            <picklistValues>
                <fullName>00:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>01:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09:00</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>10:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23:00</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Should this schedule actually run or not?</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Schedule Config</label>
    <nameField>
        <label>What does this step do?</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ScheduleTest.cls
@IsTest private class ScheduleTest {

    static testmethod void hasTheCorrectLimits() {
        //arrange
        ApexClassModel.ESB esb = ApexClassModel.esbFromEsb(Schedule.class);
        
        //assert
        Integer expectedLimits = 100;
        Integer actualLimits = esb.Limits;
        System.assertEquals(expectedLimits, actualLimits);
    }

   static testmethod void withinSystemLimits() {
        //arrange
        ApexClassModel.ESB esb = ApexClassModel.esbFromEsb(Schedule.class);
        
        //arrange
        Map<String,Object> inputEvent = new Map<String,Object> {};
        
        //act
        Test.startTest();
        Integer limits = esb.Limits;
        Integer counter = 0;
        for (Integer i = 0; i < limits; i++) {
            ApexClassModel.BaseProcess process = new Schedule();
            List<Map<String,Object>> outputs = process.test(inputEvent);
            counter++;
        }
        Test.stopTest();

        //assert
        System.assertEquals(limits, counter, 'Limit not reached.');
   }

    
    static testmethod void messagePassedThruUntouchedWhenIsHeartbeatEqFalse() {
        //arrange input event
        Map<String,Object> inputEvent = new Map<String,Object>();
        inputEvent.put('esb__EntryPointDatetime', System.now()); //#810
        inputEvent.put('__WasHeartbeatProcess', false);
        
        //act
        ApexClassModel.BaseProcess process = new Schedule();
        List<Map<String,Object>> outputEvents = process.test(inputEvent);
        
        //assert
        Integer expectedSize = 1;
        Integer actualSize = outputEvents.size();
        System.assertEquals(expectedSize, actualSize, 'Wrong size.');
    }
    
    static testmethod void messagePassedThruUntouchedWhenIsHeartbeatEqTrueAndIsWithinWindowReturnsTrue01() {
        //arrange config
        insert new ScheduleConfig__c(
            IsActive__c = true,
            Frequency__c = 'Weekly',
            FriendlyDates__c = 'Wednesday',
            FriendlyTimes__c = '12:00'
        );

        //arrange input
        Datetime entryPoint = Datetime.newInstanceGmt(2014, 1, 15, 12, 0, 0); //15th Jan 2014 is a Wednesday
        Map<String,Object> inputEvent = new Map<String,Object>{
            'esb__StepConfigId' => [SELECT Id FROM ScheduleConfig__c].Id,
            'esb__EntryPointDatetime' => entryPoint,
            '__WasHeartbeatProcess' => true
        };
        
        //act
        ApexClassModel.BaseProcess process = new Schedule();
        List<Map<String,Object>> outputEvents = process.test(inputEvent);
        
        //assert
        Integer expectedSize = 1;
        Integer actualSize = outputEvents.size();
        System.assertEquals(expectedSize, actualSize, 'Wrong size.');
        
        String expectedEntryPoint = '2014-01-15T12:00:00.000Z';
        String actualEntryPoint = (String)outputEvents[0].get('esb__EntryPointDatetime');
        System.assertEquals(expectedEntryPoint, actualEntryPoint, 'Wrong entry point datetime.');
    }

    static testmethod void messagePassedThruUntouchedWhenIsHeartbeatEqTrueAndIsWithinWindowReturnsTrue02() {
        //arrange config
        insert new ScheduleConfig__c(
            IsActive__c = true,
            Frequency__c = 'Daily',
            FriendlyDates__c = 'Working days only',
            FriendlyTimes__c = '12:00'
        );
        
        //arrange input
        Datetime entryPoint = Datetime.newInstanceGmt(2014, 1, 15, 12, 0, 0); //15th Jan 2014 is a Wednesday, a working day
        Map<String,Object> inputEvent = new Map<String,Object>{
            'esb__StepConfigId' => [SELECT Id FROM ScheduleConfig__c].Id,
            'esb__EntryPointDatetime' => entryPoint,
            '__WasHeartbeatProcess' => true
        };
        
        ///act on working days only
        ApexClassModel.BaseProcess process = new Schedule();
        List<Map<String,Object>> outputEvents = process.test(inputEvent);
        
        //assert
        Integer expectedSize = 1;
        Integer actualSize = outputEvents.size();
        System.assertEquals(expectedSize, actualSize, 'Wrong size.');
        
        String expectedEntryPoint = '2014-01-15T12:00:00.000Z';
        String actualEntryPoint = (String)outputEvents[0].get('esb__EntryPointDatetime');
        System.assertEquals(expectedEntryPoint, actualEntryPoint, 'Wrong entry point datetime.');
    }
    
    static testmethod void messagePassedThruUntouchedWhenIsHeartbeatEqTrueAndIsWithinWindowReturnsTrue03() {
        //arrange config
        insert new ScheduleConfig__c(
            IsActive__c = true,
            Frequency__c = 'Monthly',
            FriendlyDates__c = '03;15;16',
            FriendlyTimes__c = '12:00'
        );
        
        //arrange input
        Datetime entryPoint = Datetime.newInstanceGmt(2014, 1, 3, 12, 0, 0);
        Map<String,Object> inputEvent = new Map<String,Object>{
            'esb__StepConfigId' => [SELECT Id FROM ScheduleConfig__c].Id,
            'esb__EntryPointDatetime' => entryPoint,
            '__WasHeartbeatProcess' => true
        };
 
        //act
        ApexClassModel.BaseProcess process = new Schedule();
        List<Map<String,Object>> outputEvents = process.test(inputEvent);
        
        //assert
        Integer expectedSize = 1;
        Integer actualSize = outputEvents.size();
        System.assertEquals(expectedSize, actualSize, 'Wrong size.');
        
        String expectedEntryPoint = '2014-01-03T12:00:00.000Z';
        String actualEntryPoint = (String)outputEvents[0].get('esb__EntryPointDatetime');
        System.assertEquals(expectedEntryPoint, actualEntryPoint, 'Wrong entry point datetime.');
    }
    
    static testmethod void messageSwallowedWhenIsHeartbeatEqTrueAndIsWithinWindowReturnsFalse() {
        //arrange config
        insert new ScheduleConfig__c(
            Frequency__c = 'Weekly',
            FriendlyDates__c = 'Wednesday',
            FriendlyTimes__c = '13:00'
        );
        
        //arrange input event parameters
        Datetime entryPoint = Datetime.newInstanceGmt(2014, 1, 18, 12, 0, 0);
        Map<String,Object> inputEvent = new Map<String,Object>{
            'esb__StepConfigId' => [SELECT Id FROM ScheduleConfig__c].Id,
            'esb__EntryPointDatetime' => entryPoint,
            '__WasHeartbeatProcess' => true
        };
 
        //act
        ApexClassModel.BaseProcess process = new Schedule();
        List<Map<String,Object>> outputEvents = process.test(inputEvent);
        
        //assert
        Integer expectedSize = 0;
        Integer actualSize = outputEvents.size();
        System.assertEquals(expectedSize, actualSize, 'Wrong size.');
    }
    
    static testmethod void isHeartbeatThrowsExceptionWhenInvalidStampParam() {
        //arrange config
        insert new ScheduleConfig__c(
            IsActive__c = true
        );
        
        //arrange input
        Datetime entryPoint = null;
        Map<String,Object> inputEvent = new Map<String,Object>{
            'esb__StepConfigId' => [SELECT Id FROM ScheduleConfig__c].Id,
            'esb__EntryPointDatetime' => entryPoint,
            '__WasHeartbeatProcess' => true
        };
        
        try {
            //act
            ApexClassModel.BaseProcess process =  new Schedule();
            process.test(inputEvent);
            System.assert(false, 'Line above should throw exception.');
        } catch (Exception e) {
            //assert
            String expectedMessage = 'Problem with getISO8601 or getStamp("null")';
            String actualMessage = e.getMessage();
            System.assertEquals(expectedMessage, actualMessage, 'Wrong message.');
        }
    }
    
    static testmethod void callingIsTimeMatchReturnsTrueWhenTimeStampIsInRunTimes() {
        //arrange
        Set<String> runTimesA = new Set<String>{'12:00','11:00'};
        Set<String> runTimesB = new Set<String>{'12:00'};
        String stampAsString1 = '2014-01-18T12:00:00.000Z';
        String stampAsString2 = '2014-01-18 12:00:00.000';
        String stampAsString3 = '2014-01-18T12:00:00';
        
        //act and assert
        System.assert(Schedule.isTimeMatch(stampAsString1, runTimesA));
        System.assert(Schedule.isTimeMatch(stampAsString1, runTimesA));
        System.assert(Schedule.isTimeMatch(stampAsString1, runTimesA));
        System.assert(Schedule.isTimeMatch(stampAsString1, runTimesB));
        System.assert(Schedule.isTimeMatch(stampAsString1, runTimesB));
        System.assert(Schedule.isTimeMatch(stampAsString1, runTimesB));
    }
    
    static testmethod void testDailyWindow() {
        //arrange
        DateTime sundayNight = DateTime.newInstance(2014, 1, 19, 23, 59, 59); //19th Jan 2014 is a Sunday
        DateTime wednesday = DateTime.newInstance(2014, 1, 15, 0, 0, 0); //15th Jan 2014 is a Wednesday
        
        //act and assert
        System.assert(!Schedule.isWithinDailyWindow(sundayNight, new Set<String>{'Working days only'}));
        System.assert(Schedule.isWithinDailyWindow(sundayNight, new Set<String>{'Weekends and holidays'}));
        System.assert(Schedule.isWithinDailyWindow(sundayNight, new Set<String>{'Working days only','Weekends and holidays'}));
        System.assert(Schedule.isWithinDailyWindow(wednesday, new Set<String>{'Working days only','Weekends and holidays'}));
    }
    
    static testmethod void testWeeklyWindow() {
        //arrange
        DateTime wednesday = DateTime.newInstance(2014, 1, 15, 9, 0, 0); //15th Jan 2014 is a Wednesday
        DateTime saturdayMorning = DateTime.newInstance(2014, 1, 18, 0, 0, 1); //18th Jan 2014 is a Satuday
        DateTime saturdayNight = DateTime.newInstance(2014, 1, 18, 23, 59, 59); //18th Jan 2014 is a Saturday
        
        //act and assert
        System.assert(Schedule.isWithinWeeklyWindow(wednesday, new Set<String>{'Tuesday', 'Wednesday', 'Thursday'}));
        System.assert(!Schedule.isWithinWeeklyWindow(wednesday, new Set<String>{'Thursday', 'Saturday'}));
        System.assert(!Schedule.isWithinWeeklyWindow(saturdayMorning, new Set<String>{'Friday'}));
        System.assert(Schedule.isWithinWeeklyWindow(saturdayMorning, new Set<String>{'Saturday'}));
        System.assert(!Schedule.isWithinWeeklyWindow(saturdayMorning, new Set<String>{'Sunday'}));
        System.assert(!Schedule.isWithinWeeklyWindow(saturdayNight, new Set<String>{'Friday'}));
        System.assert(Schedule.isWithinWeeklyWindow(saturdayNight, new Set<String>{'Saturday'}));
        System.assert(!Schedule.isWithinWeeklyWindow(saturdayNight, new Set<String>{'Sunday'}));
    }
    
    static testmethod void testMonthlyWindow() {
        //arrange
        String christmasMorning = '2014-12-25T12:09:00.000Z';
        String newYearsDay = '2014-01-01T12:09:00.000Z';
        String independenceDay = '2014-07-04T12:09:00';

        //act and assert
        System.assert(Schedule.isWithinMonthlyWindow(christmasMorning, new Set<String>{'24', '25', '26'}));
        System.assert(!Schedule.isWithinMonthlyWindow(newYearsDay, new Set<String>{'06', '02', '03'}));
        System.assert(Schedule.isWithinMonthlyWindow(independenceDay, new Set<String>{'04'}));
    }
     
}