src/objects/Sequence__c.object
<CustomObject>
    <customHelpPage>SequenceHelp</customHelpPage>
    <label>Sequence</label>
    <nameField>
        <label>Sequence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Step__c.object
<CustomObject>
    <fields>
        <fullName>Position__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Position</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Step</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SubsequenceConfig__c.object
<CustomObject>
    <customHelpPage>SubsequenceConfigCsh</customHelpPage>
    <fields>
        <fullName>Sequence__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Through which sequence should messages be diverted, before they progress to the next step?</inlineHelpText>
        <label>Sequence</label>
        <referenceTo>Sequence__c</referenceTo>
        <relationshipLabel>Subsequence Config</relationshipLabel>
        <relationshipName>SubsequenceConfig</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subsequence Config</label>
    <nameField>
        <label>What does this step do?</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsequence Config</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Subsequence.cls
public with sharing class Subsequence extends ProcessModel.BaseProcess {
    
    public SubsequenceConfig__c StepConfig;
    
    /**
     * @docs ProcessBranchJumpSubsequence.html
     */
    public class ESB {
        public String Tag = 'Enterprise Service Bus';
        public String Name = 'Subsequence';
        public String Description = 'Temporarily diverts the message to another sequence, then returns it to the next step afterwards.';
        public SObject StepConfig = SubsequenceConfig__c.SObjectType.newSObject();
        public String Icon = 'arrow_undo';
        public String HelpUrl = new PageReference('/apex/Csh?topic=ProcessBranchJumpSubsequence').getUrl();
        public Integer Limits = 50; //leave half of 200 (Total number of SOQL queries issued)
        public String Cardinality = 'One';
    }
    
    override protected List<Map<String,Object>> execute(Map<String,Object> parameters) {
        
        //derive the step Id
        Step__c step = [
            SELECT Id
            FROM Step__c
            WHERE Sequence__r.Name = :(String)parameters.get('__SequenceName')
            AND Position__c = :(Decimal) parameters.get('__Position')
        ];
  
        //get destination from config
        SubsequenceConfig__c config = this.StepConfig;
        Sequence__c sequence = (Sequence__c)ApexDomain.getById(config.Sequence__c);
        
        List<Object> stepIds = (List<Object>)parameters.get('__SubsequenceStepIds');
        if (stepIds == null) {
            stepIds = new List<Object>();
        }
        stepIds.add(step.Id);
        
        parameters.put('__SubsequenceStepIds', stepIds);
        parameters.put('__SequenceName', sequence.Name);
        parameters.put('__Position', 0);
        
        return new List<Map<String,Object>>{parameters};
    }
}