src/objects/Step__c.object
<CustomObject>
    <fields>
        <fullName>ConfigurationId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>ConfigurationId</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Step</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/StepShowConfigurationExtension.cls
public with sharing class StepShowConfigurationExtension {
    
    private ApexPages.StandardController controller;
    
    public StepShowConfigurationExtension(ApexPages.StandardController controller) {
        this.controller = controller;
    }
    
    /**
     * This resolves the Configuration record for a given Step so that
     * it can be accessed from the native interface via a Custom Button.
     */
    public PageReference doRedirect() {
        Step__c step = (Step__c)SalesforceObject.getById(this.controller.getId());
        if (null == step.ConfigurationId__c) {
            //process has no configuration, go back
            return new ApexPages.StandardController(step).view();
        } else {
            //real config exists, show detail page
            return new ApexPages.StandardController(SalesforceObject.getById(step.ConfigurationId__c)).view();
        }
    }
    
}