src/objects/WiretapSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Define where Wiretap emails are sent</description>
    <fields>
        <fullName>UserId__c</fullName>
        <defaultValue>$User.Id</defaultValue>
        <description>Id of the user who will receive Wiretap emails</description>
        <externalId>true</externalId>
        <inlineHelpText>Id of the user who will receive Wiretap emails</inlineHelpText>
        <label>User Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Wiretap Settings</label>
</CustomObject>

src/classes/WiretapTest.cls
@isTest //-- no view of org data
private class WiretapTest {
    
    static testMethod void testProcessIsDescribed() {
        Wiretap wiretap = new Wiretap();
        System.assertNotEquals(null, wiretap.describe().Name);
        System.assertNotEquals(null, wiretap.describe().Description);
        System.assertNotEquals(null, wiretap.describe().Tag);
    }
    
    static testMethod void callingInvokeWillNOTThrowExpectedWhenUserIdOnCustomSettingNOTSet() {
        // Arrange :
        String sequenceName = 'the-sequence';
        Integer step = 1;
        String data = 'data';

       //--NOT-DEFINED insert new WiretapSettings__c ( UserId__c = UserInfo.getUserId());

        Map<String,Object> parameters = new Map<String,Object> {
            'eda_SequenceName' => sequenceName,
            'eda_Step' => step,
            'data' => data
        };
        

   

        // Act
        Wiretap wireTap = new Wiretap();
        Boolean actualFlagException = false;
        try {
            Process.PluginResult results = wireTap.invoke(new Process.PluginRequest(parameters));
        } catch (Exception e) {
           actualFlagException = true;
        }
        
 
        // Assert
        Boolean expectedFlagException = false;
        System.assertEquals(expectedFlagException , actualFlagException );
    }
   
    static testMethod void callingExecuteReturnsExpectedParametersCollectionWhenDefinedMetaCustomSettingSet() {
        // Arrange :
        String sequenceName = 'the-sequence';
        Integer step = 1;
        String data = 'data';

        insert new WiretapSettings__c ( UserId__c = UserInfo.getUserId());

        Map<String,Object> parameters = new Map<String,Object> {
            'eda_SequenceName' => sequenceName,
            'eda_Step' => step,
            'data' => data
        };
        

        Integer expectedSize = 1;

        // Act
        Wiretap wireTap = new Wiretap();
        Process.PluginResult results = wireTap.invoke(new Process.PluginRequest(parameters));
        List<Map<String,Object>> actualParametersList = EdaUtility.convert(results);

        // prepare
        Integer actualSize = actualParametersList.size();

        // Assert
        System.assertEquals(expectedSize , actualSize );
    }
}